/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.util.ArrayList;
import proyectobd.dao.mysql.MySQLEmpresa;
import proyectobd.dao.mysql.MySQLMarcaPieza;
import proyectobd.dao.mysql.MySQLNombrePieza;
import proyectobd.dao.mysql.MySQLProveedor;
import proyectobd.dao.mysql.MySQLTelefonoProveedor;
import proyectobd.modelos.Empresa;
import proyectobd.modelos.NombrePieza;
import proyectobd.modelos.Proveedor;
import proyectobd.modelos.TelefonoProveedor;
import proyectobd.modelos.MarcaPieza;

public class Agregar extends javax.swing.JFrame {
    public static int tipo = 0;

    public Agregar() {
        initComponents();
        this.setLocationRelativeTo(null);
        texto1.setVisible(false);texto2.setVisible(false);texto3.setVisible(false);texto4.setVisible(false);texto5.setVisible(false);texto6.setVisible(false);
        input1.setVisible(false);input2.setVisible(false);input3.setVisible(false);input4.setVisible(false);input5.setVisible(false);input6.setVisible(false);
        switch(tipo){
            case 1:
                this.titulo.setText("AGREGAR NOMBRE DE PIEZA");
                texto1.setText("NOMBRE: ");texto1.setVisible(true);
                input1.setText("");input1.setVisible(true);
                break;
            case 2:
                this.titulo.setText("AGREGAR PROVEEDOR");
                texto1.setText("NOMBRE: ");texto1.setVisible(true);
                input1.setText("");input1.setVisible(true);
                texto2.setText("DIRECCION: ");texto2.setVisible(true);
                input2.setText("");input2.setVisible(true);
                texto3.setText("TELEFONO 1: ");texto3.setVisible(true);
                input3.setText("");input3.setVisible(true);
                texto4.setText("TELEFONO 2: ");texto4.setVisible(true);
                input4.setText("");input4.setVisible(true);
                break;
            case 3:
                this.titulo.setText("AGREGAR EMPRESA");
                texto1.setText("NOMBRE: ");texto1.setVisible(true);
                input1.setText("");input1.setVisible(true);
                texto2.setText("DIRECCION: ");texto2.setVisible(true);
                input2.setText("");input2.setVisible(true);
                texto3.setText("NIT: ");texto3.setVisible(true);
                input3.setText("");input3.setVisible(true);
                break;
            case 4:
                this.titulo.setText("AGREGAR MARCA DE PIEZA");
                texto1.setText("MARCA: ");texto1.setVisible(true);
                input1.setText("");input1.setVisible(true);
                break;
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        texto1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        texto2 = new javax.swing.JLabel();
        texto3 = new javax.swing.JLabel();
        texto4 = new javax.swing.JLabel();
        texto5 = new javax.swing.JLabel();
        texto6 = new javax.swing.JLabel();
        input1 = new javax.swing.JTextField();
        input2 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        input4 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        input6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        cerrar = new javax.swing.JLabel();
        Errores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_mas.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 50));

        titulo.setBackground(new java.awt.Color(252, 100, 68));
        titulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        titulo.setForeground(new java.awt.Color(252, 100, 68));
        titulo.setText("TITULO");
        jPanel1.add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 350, 30));

        texto1.setBackground(new java.awt.Color(252, 100, 68));
        texto1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto1.setForeground(new java.awt.Color(252, 100, 68));
        texto1.setText("TEXTO");
        jPanel1.add(texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 160, 30));

        jSeparator1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 380, 20));

        texto2.setBackground(new java.awt.Color(252, 100, 68));
        texto2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto2.setForeground(new java.awt.Color(252, 100, 68));
        texto2.setText("TEXTO");
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 160, 30));

        texto3.setBackground(new java.awt.Color(252, 100, 68));
        texto3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto3.setForeground(new java.awt.Color(252, 100, 68));
        texto3.setText("TEXTO");
        jPanel1.add(texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 160, 30));

        texto4.setBackground(new java.awt.Color(252, 100, 68));
        texto4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto4.setForeground(new java.awt.Color(252, 100, 68));
        texto4.setText("TEXTO");
        jPanel1.add(texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 160, 30));

        texto5.setBackground(new java.awt.Color(252, 100, 68));
        texto5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto5.setForeground(new java.awt.Color(252, 100, 68));
        texto5.setText("TEXTO");
        jPanel1.add(texto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 160, 30));

        texto6.setBackground(new java.awt.Color(252, 100, 68));
        texto6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        texto6.setForeground(new java.awt.Color(252, 100, 68));
        texto6.setText("TEXTO");
        jPanel1.add(texto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 160, 30));

        input1.setText("INPUT1");
        input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input1ActionPerformed(evt);
            }
        });
        jPanel1.add(input1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 220, 30));

        input2.setText("INPUT1");
        input2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input2ActionPerformed(evt);
            }
        });
        jPanel1.add(input2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 220, 30));

        input3.setText("INPUT1");
        input3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input3ActionPerformed(evt);
            }
        });
        jPanel1.add(input3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 220, 30));

        input4.setText("INPUT1");
        input4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input4ActionPerformed(evt);
            }
        });
        jPanel1.add(input4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 220, 30));

        input5.setText("INPUT1");
        input5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input5ActionPerformed(evt);
            }
        });
        jPanel1.add(input5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 220, 30));

        input6.setText("INPUT1");
        input6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input6ActionPerformed(evt);
            }
        });
        jPanel1.add(input6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 220, 30));

        jButton1.setBackground(new java.awt.Color(252, 100, 68));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("AGREGAR");
        jButton1.setToolTipText("");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 380, 40));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, 30));
        jPanel1.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input1ActionPerformed

    private void input2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input2ActionPerformed

    private void input3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input3ActionPerformed

    private void input4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input4ActionPerformed

    private void input5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input5ActionPerformed

    private void input6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input6ActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch(this.tipo){
            case 1:
                boolean existePieza = false;
                MySQLNombrePieza auxPieza = new MySQLNombrePieza();
                NombrePieza pieza = new NombrePieza();
                if(!input1.getText().equals("")){
                    pieza.setNombre(input1.getText());
                    ArrayList <NombrePieza> listaNombrePieza = auxPieza.listar();
                    for(int i = 0; i < listaNombrePieza.size();i++){
                        if(pieza.getNombre().toUpperCase().equals(listaNombrePieza.get(i).getNombre())){
                            existePieza = true;
                            Errores.setText("EL dato que desea ingresar ya existe.");
                        }
                    }
                    if(!existePieza){
                        auxPieza.insertar(pieza);
                        listaNombrePieza = auxPieza.listar();
                        for(int i = 0; i<listaNombrePieza.size()-1;i++){
                            Detalle.nombrePieza.removeItemAt(1);
                        }
                        for(int i = 0; i<listaNombrePieza.size();i++){
                            Detalle.nombrePieza.addItem(listaNombrePieza.get(i).getNombre());
                        }
                        dispose();
                    }
                    Detalle.nombrePieza.setSelectedIndex(0);
                    
                }else{
                    Errores.setText("No puede haber campos vacios.");
                }
                break;
            case 2:
                boolean existeProveedor = false;
                MySQLProveedor auxProveedor = new MySQLProveedor();
                MySQLTelefonoProveedor auxTelefonoProveedor = new MySQLTelefonoProveedor();
                
                Proveedor proveedor = new Proveedor();
                TelefonoProveedor TelefonoProveedor1 = new TelefonoProveedor();
                TelefonoProveedor TelefonoProveedor2 = new TelefonoProveedor();
                
                if(!input1.getText().equals("") && !input2.getText().equals("") && !input3.getText().equals("") && !input4.getText().equals("")){
                    proveedor.setNombre(input1.getText());
                    proveedor.setDireccion(input2.getText());
                    TelefonoProveedor1.setNumero(Integer.parseInt(input3.getText()));
                    TelefonoProveedor2.setNumero(Integer.parseInt(input4.getText()));
                    
                    ArrayList <Proveedor> listaProveedor = auxProveedor.listar();
                    
                    for(int i = 0; i < listaProveedor.size();i++){
                        if(proveedor.getNombre().toUpperCase().equals(listaProveedor.get(i).getNombre())){
                            existeProveedor = true;
                            Errores.setText("EL dato que desea ingresar ya existe.");
                        }
                    }
                    if(!existeProveedor){
                        auxProveedor.insertar(proveedor);
                        listaProveedor = auxProveedor.listar();

                        TelefonoProveedor1.setIdProveedor(listaProveedor.get(listaProveedor.size()-1).getIdProveedor());
                        TelefonoProveedor2.setIdProveedor(listaProveedor.get(listaProveedor.size()-1).getIdProveedor());

                        auxTelefonoProveedor.insertar(TelefonoProveedor1);
                        auxTelefonoProveedor.insertar(TelefonoProveedor2);

                        for(int i = 0; i<listaProveedor.size()-1;i++){
                            Detalle.proveedor.removeItemAt(1);
                        }
                        for(int i = 0; i<listaProveedor.size();i++){
                            Detalle.proveedor.addItem(listaProveedor.get(i).getNombre());
                        }
                        dispose();
                   }
                   Detalle.nombrePieza.setSelectedIndex(0);
                }else{
                    Errores.setText("No puede haber campos vacios.");
                }
                
                break;
            case 3:
                boolean existeEmpresa = false;
                MySQLEmpresa auxEmpresa = new MySQLEmpresa();
                Empresa empresa = new Empresa();
                
                if(!input1.getText().equals("") && !input2.getText().equals("") && !input3.getText().equals("")){
                    empresa.setNombre(input1.getText());
                    empresa.setDireccion(input2.getText());
                    empresa.setNit(input3.getText());
                    ArrayList <Empresa> listaEmpresa = auxEmpresa.listar();
                    for(int i = 0; i < listaEmpresa.size();i++){
                        if(empresa.getNombre().toUpperCase().equals(listaEmpresa.get(i).getNombre())){
                            existeEmpresa = true;
                            Errores.setText("EL dato que desea ingresar ya existe.");
                        }
                    }
                    if(!existeEmpresa){
                        auxEmpresa.insertar(empresa);
                        listaEmpresa = auxEmpresa.listar();
                        for(int i = 0; i<listaEmpresa.size()-1;i++){
                            CompraPiezaFrame.empresa.removeItemAt(1);
                        }
                        for(int i = 0; i<listaEmpresa.size();i++){
                            CompraPiezaFrame.empresa.addItem(listaEmpresa.get(i).getNombre());
                        }
                        dispose();
                    }
                    CompraPiezaFrame.empresa.setSelectedIndex(0);
                }else{
                    Errores.setText("No puede haber campos vacios.");
                }
                break;
            case 4:
                boolean existeMarcaPieza = false;
                MySQLMarcaPieza auxMarcaPieza = new MySQLMarcaPieza();
                MarcaPieza marcaPieza = new MarcaPieza();
                if(!input1.getText().equals("")){
                    marcaPieza.setMarca(input1.getText());
                    ArrayList <MarcaPieza> listaMarcaPieza = auxMarcaPieza.listar();
                    for(int i = 0; i < listaMarcaPieza.size();i++){
                        if(marcaPieza.getMarca().toUpperCase().equals(listaMarcaPieza.get(i).getMarca())){
                            existeMarcaPieza = true;
                            Errores.setText("EL dato que desea ingresar ya existe.");
                        }
                    }
                    if(!existeMarcaPieza){
                        auxMarcaPieza.insertar(marcaPieza);
                        listaMarcaPieza = auxMarcaPieza.listar();
                        for(int i = 0; i<listaMarcaPieza.size()-1;i++){
                            Detalle.marcaPieza.removeItemAt(1);
                        }
                        for(int i = 0; i<listaMarcaPieza.size();i++){
                            Detalle.marcaPieza.addItem(listaMarcaPieza.get(i).getMarca());
                        }
                        dispose();
                    }
                    Detalle.marcaPieza.setSelectedIndex(0);
                }else{
                    Errores.setText("No puede haber campos vacios.");  
                }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252,100,68)));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agregar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Errores;
    private javax.swing.JLabel cerrar;
    private javax.swing.JTextField input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JTextField input6;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel texto1;
    private javax.swing.JLabel texto2;
    private javax.swing.JLabel texto3;
    private javax.swing.JLabel texto4;
    private javax.swing.JLabel texto5;
    private javax.swing.JLabel texto6;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
