/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import proyectobd.dao.mysql.MySQLCarro;
import proyectobd.dao.mysql.MySQLEstadoPieza;
import proyectobd.dao.mysql.MySQLMarcaPieza;
import proyectobd.dao.mysql.MySQLNombrePieza;
import proyectobd.dao.mysql.MySQLPieza;
import proyectobd.dao.mysql.MySQLProveedor;
import proyectobd.modelos.Carro;
import proyectobd.modelos.DetalleFacturaCompra;
import proyectobd.modelos.EstadoPieza;
import proyectobd.modelos.MarcaPieza;
import proyectobd.modelos.NombrePieza;
import proyectobd.modelos.Pieza;
import proyectobd.modelos.Proveedor;
import static proyectobd.vistas.modulo.compraVenta.CompraPiezaFrame.realizarVenta;

/**
 *
 * @author ricar
 */
public class Detalle extends javax.swing.JFrame {
    public static int tipo = 0;
    public static double total = 0.00;
    public static ArrayList <DetalleFacturaCompra> listaDetalleFacturaCompra = new ArrayList();
    
    /**
     * Creates new form Detalle
     */
    public Detalle() {
        initComponents();
        this.setLocationRelativeTo(null);
        MySQLNombrePieza aux = new MySQLNombrePieza();
        MySQLProveedor aux2 = new MySQLProveedor();
        MySQLEstadoPieza aux3 = new MySQLEstadoPieza();
        MySQLMarcaPieza aux4 = new MySQLMarcaPieza();
        
        
        ArrayList <NombrePieza> listaNombrePieza = aux.listar();
        ArrayList <Proveedor> listaProveedor = aux2.listar();
        ArrayList <EstadoPieza> listaEstadoPieza = aux3.listar();
        ArrayList <MarcaPieza> listaMarcaPieza = aux4.listar();
        
        for(int i = 0; i<listaNombrePieza.size();i++){
            nombrePieza.addItem(listaNombrePieza.get(i).getNombre());
        }
        for(int i = 0; i<listaProveedor.size();i++){
            proveedor.addItem(listaProveedor.get(i).getNombre());
        }
        for(int i = 0; i<listaEstadoPieza.size();i++){
            estado.addItem(listaEstadoPieza.get(i).getEstado());
        }
        for(int i = 0; i<listaMarcaPieza.size();i++){
            marcaPieza.addItem(listaMarcaPieza.get(i).getMarca());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        proveedor = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nombrePieza = new javax.swing.JComboBox<>();
        AgregarNombrePieza = new javax.swing.JButton();
        AgregarProveedor = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        Cantidad = new javax.swing.JSpinner();
        jSeparator4 = new javax.swing.JSeparator();
        estado = new javax.swing.JComboBox<>();
        marcaPieza = new javax.swing.JComboBox<>();
        AgregarMarcaPieza = new javax.swing.JButton();
        año = new javax.swing.JTextField();
        marca = new javax.swing.JTextField();
        linea = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        Errores = new javax.swing.JLabel();
        TotalDesing = new javax.swing.JLabel();
        NumeroPieza = new javax.swing.JFormattedTextField();
        PrecioCompra = new javax.swing.JFormattedTextField();
        PrecioVenta = new javax.swing.JFormattedTextField();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setMinimumSize(new java.awt.Dimension(950, 525));
        jPanel1.setPreferredSize(new java.awt.Dimension(950, 525));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROVEEDOR" }));
        proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proveedorActionPerformed(evt);
            }
        });
        jPanel1.add(proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 30));

        jLabel5.setBackground(new java.awt.Color(252, 100, 68));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 100, 68));
        jLabel5.setText("PROVEEDOR:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, 30));

        jLabel4.setBackground(new java.awt.Color(252, 100, 68));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(252, 100, 68));
        jLabel4.setText("NOMBRE DE PIEZA:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 30));

        nombrePieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOMBRE DE PIEZA" }));
        nombrePieza.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        nombrePieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombrePiezaActionPerformed(evt);
            }
        });
        jPanel1.add(nombrePieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 150, 30));

        AgregarNombrePieza.setText("+");
        AgregarNombrePieza.setToolTipText("");
        AgregarNombrePieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarNombrePiezaActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarNombrePieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 110, 50, 30));

        AgregarProveedor.setText("+");
        AgregarProveedor.setToolTipText("");
        AgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 50, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_pieza_mini.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        jLabel1.setBackground(new java.awt.Color(252, 100, 68));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 100, 68));
        jLabel1.setText("DETALLE DE COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 10));

        jLabel6.setBackground(new java.awt.Color(252, 100, 68));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 100, 68));
        jLabel6.setText("PRECIO DE COMPRA:");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, 30));

        jLabel7.setBackground(new java.awt.Color(252, 100, 68));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 100, 68));
        jLabel7.setText("PRECIO DE VENTA:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, 30));

        jLabel8.setBackground(new java.awt.Color(252, 100, 68));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 100, 68));
        jLabel8.setText("CANTIDAD:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 270, -1, 30));

        jLabel9.setBackground(new java.awt.Color(252, 100, 68));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 100, 68));
        jLabel9.setText("NUMERO DE PIEZA:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, -1, 30));

        jLabel10.setBackground(new java.awt.Color(252, 100, 68));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(252, 100, 68));
        jLabel10.setText("ESTADO DE PIEZA:");
        jLabel10.setToolTipText("");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 30));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 10, -1, 30));

        jLabel11.setBackground(new java.awt.Color(252, 100, 68));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 100, 68));
        jLabel11.setText("MARCA DE PIEZA:");
        jLabel11.setToolTipText("");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, 30));

        jLabel12.setBackground(new java.awt.Color(252, 100, 68));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 100, 68));
        jLabel12.setText("CARRO:");
        jLabel12.setToolTipText("");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, 30));

        jButton1.setBackground(new java.awt.Color(252, 100, 68));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("TERMINAR");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 420, 40));

        jLabel14.setBackground(new java.awt.Color(252, 100, 68));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(252, 100, 68));
        jLabel14.setText("Q/u");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 30, 30));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 200, 20));

        jLabel15.setBackground(new java.awt.Color(252, 100, 68));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(252, 100, 68));
        jLabel15.setText("Q/u");
        jLabel15.setToolTipText("");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 30, 30));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 200, 20));

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantidad.setBorder(null);
        jPanel1.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 200, 30));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 200, 20));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTADO" }));
        estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estadoActionPerformed(evt);
            }
        });
        jPanel1.add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 200, 30));

        marcaPieza.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MARCA" }));
        marcaPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaPiezaActionPerformed(evt);
            }
        });
        jPanel1.add(marcaPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 150, 30));

        AgregarMarcaPieza.setText("+");
        AgregarMarcaPieza.setToolTipText("");
        AgregarMarcaPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarMarcaPiezaActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarMarcaPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 390, 50, 30));

        año.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        año.setForeground(new java.awt.Color(252, 100, 68));
        año.setText("AÑO");
        año.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                añoMouseClicked(evt);
            }
        });
        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });
        jPanel1.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 430, 60, 30));

        marca.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        marca.setForeground(new java.awt.Color(252, 100, 68));
        marca.setText("MARCA");
        marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                marcaMouseClicked(evt);
            }
        });
        marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcaActionPerformed(evt);
            }
        });
        jPanel1.add(marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 110, 30));

        linea.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        linea.setForeground(new java.awt.Color(252, 100, 68));
        linea.setText("LINEA");
        linea.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                lineaCaretUpdate(evt);
            }
        });
        linea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lineaMouseClicked(evt);
            }
        });
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });
        jPanel1.add(linea, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 110, 30));

        jButton2.setBackground(new java.awt.Color(252, 100, 68));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 330, 40));

        tabla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabla.setForeground(new java.awt.Color(252, 100, 68));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID pieza", "Nombre ", "Precio", "Cantidad", "Marca", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(252, 100, 68));
        tabla.setSelectionBackground(new java.awt.Color(252, 100, 68));
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 420, 320));
        jPanel1.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 930, -1));

        TotalDesing.setBackground(new java.awt.Color(252, 100, 68));
        TotalDesing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalDesing.setForeground(new java.awt.Color(252, 100, 68));
        TotalDesing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalDesing.setText("TOTAL: 0.00Q ");
        TotalDesing.setToolTipText("");
        jPanel1.add(TotalDesing, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 170, 30));

        NumeroPieza.setBorder(null);
        NumeroPieza.setForeground(new java.awt.Color(252, 100, 68));
        NumeroPieza.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        NumeroPieza.setToolTipText("");
        NumeroPieza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NumeroPiezaKeyTyped(evt);
            }
        });
        jPanel1.add(NumeroPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 200, 30));

        PrecioCompra.setBorder(null);
        PrecioCompra.setForeground(new java.awt.Color(252, 100, 68));
        PrecioCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        PrecioCompra.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PrecioCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioCompraKeyTyped(evt);
            }
        });
        jPanel1.add(PrecioCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 160, 30));

        PrecioVenta.setBorder(null);
        PrecioVenta.setForeground(new java.awt.Color(252, 100, 68));
        PrecioVenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        PrecioVenta.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        PrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioVentaActionPerformed(evt);
            }
        });
        PrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioVentaKeyTyped(evt);
            }
        });
        jPanel1.add(PrecioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 160, 30));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 200, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_proveedorActionPerformed

    private void nombrePiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombrePiezaActionPerformed

    }//GEN-LAST:event_nombrePiezaActionPerformed

    private void AgregarNombrePiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarNombrePiezaActionPerformed
        Agregar.tipo = 1;
        Agregar append = new Agregar();
        append.setVisible(true);
    }//GEN-LAST:event_AgregarNombrePiezaActionPerformed

    private void AgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProveedorActionPerformed
        Agregar.tipo = 2;
        Agregar append = new Agregar();
        append.setVisible(true);
    }//GEN-LAST:event_AgregarProveedorActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estadoActionPerformed

    private void marcaPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaPiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaPiezaActionPerformed

    private void AgregarMarcaPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarMarcaPiezaActionPerformed
        Agregar.tipo = 4;
        Agregar append = new Agregar();
        append.setVisible(true);
    }//GEN-LAST:event_AgregarMarcaPiezaActionPerformed

    private void marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_marcaMouseClicked
        marca.setText("");
    }//GEN-LAST:event_marcaMouseClicked

    private void lineaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lineaMouseClicked
        linea.setText("");
    }//GEN-LAST:event_lineaMouseClicked

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        
    }//GEN-LAST:event_añoActionPerformed

    private void añoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_añoMouseClicked
        año.setText("");
    }//GEN-LAST:event_añoMouseClicked
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Errores.setText("");
        DetalleFacturaCompra nuevoDetalle = new DetalleFacturaCompra();
        DefaultTableModel model = (DefaultTableModel)tabla.getModel();
        
        MySQLCarro auxCarro = new MySQLCarro();
        MySQLPieza auxPieza = new MySQLPieza(); 
        MySQLProveedor auxProveedor = new MySQLProveedor();
        MySQLNombrePieza auxNombrePieza = new MySQLNombrePieza();
        MySQLEstadoPieza auxEstadoPieza = new MySQLEstadoPieza();
        MySQLMarcaPieza auxMarcaPieza = new MySQLMarcaPieza();
        
        Carro nuevoCarro = new Carro();
        
        
        ArrayList <Carro> listaCarro = auxCarro.listar();
        ArrayList <Proveedor> listaProveedor  = auxProveedor.listar();
        ArrayList <NombrePieza> listaNombrePieza  = auxNombrePieza.listar();
        ArrayList <EstadoPieza> listaEstadoPieza  = auxEstadoPieza.listar();
        ArrayList <MarcaPieza> listaMarcaPieza  = auxMarcaPieza.listar();
        
        boolean existePieza = false;
        boolean existeCarro = false;
        int indexCarro = 0; 
        int indexProveedor = 0;
        int indexNombrePieza = 0;
        int indexEstadoPieza = 0;
        int indexMarcaPieza = 0;
        int indexPieza = 0;
        int cantidadCompra;
        
        String TablaIDPieza = "N/A";
        String TablaNombrePieza = "N/A";
        double TablaPrecio = 0.00;
        int TablaCantidad = 0;
        String TablaMarca = "N/A";
        double TablaSubtotal = 0.00;
        
        
        boolean vacio1 = (nombrePieza.getSelectedIndex() == 0);
        boolean vacio2 = (proveedor.getSelectedIndex() == 0);
        boolean vacio3 = PrecioCompra.getText().equals("");
        boolean vacio4 = PrecioVenta.getText().equals("");
        boolean vacio5 = ((Integer)Cantidad.getValue() == 0);
        boolean vacio6 = NumeroPieza.getText().equals("");
        boolean vacio7 = (estado.getSelectedIndex() == 0);
        boolean vacio8 = (marcaPieza.getSelectedIndex() == 0);
        boolean vacio9 = (marca.getText().equals("") || marca.getText().equals("MARCA"))||(linea.getText().equals("") || linea.getText().equals("MODELO"))||(año.getText().equals("") || año.getText().equals("AÑO"));
        
        if(!vacio1 && !vacio2 && !vacio3 && !vacio4 && !vacio5 && !vacio6 && !vacio7 && !vacio8 && !vacio9){
            cantidadCompra = (Integer)Cantidad.getValue();
            nuevoCarro.setMarca(marca.getText());
            nuevoCarro.setLinea(linea.getText());
            nuevoCarro.setModelo(año.getText());
            for(int i = 0; i < listaProveedor.size(); i++){
                if(proveedor.getSelectedItem().equals(listaProveedor.get(i).getNombre())){
                    indexProveedor = listaProveedor.get(i).getIdProveedor();
                }
            }
            for(int i = 0; i < listaNombrePieza.size(); i++){
                if(nombrePieza.getSelectedItem().equals(listaNombrePieza.get(i).getNombre())){
                    indexNombrePieza = listaNombrePieza.get(i).getIdNombrePieza();
                    TablaNombrePieza = listaNombrePieza.get(i).getNombre();
                }
            }
            for(int i = 0; i < listaEstadoPieza.size(); i++){
                if(estado.getSelectedItem().equals(listaEstadoPieza.get(i).getEstado())){
                    indexEstadoPieza = listaEstadoPieza.get(i).getIdEstadoPieza();
                }
            }
            for(int i = 0; i < listaMarcaPieza.size(); i++){
                if(marcaPieza.getSelectedItem().equals(listaMarcaPieza.get(i).getMarca())){
                    indexMarcaPieza = listaMarcaPieza.get(i).getIdMarcaPieza();
                    TablaMarca = listaMarcaPieza.get(i).getMarca();
                }
            }
            for(int i = 0; i < listaCarro.size(); i++){
                if(nuevoCarro.getMarca().toUpperCase().equals(listaCarro.get(i).getMarca())){
                    if(nuevoCarro.getLinea().toUpperCase().equals(listaCarro.get(i).getLinea())){
                        if(nuevoCarro.getModelo().equals(listaCarro.get(i).getModelo())){
                            existeCarro = true;
                            indexCarro = listaCarro.get(i).getIdCarro();
                        }
                    }
                }
            }
            if(!existeCarro){
                auxCarro.insertar(nuevoCarro);
                listaCarro = auxCarro.listar();
                for(int i = 0; i < listaCarro.size(); i++){
                    if(nuevoCarro.getMarca().toUpperCase().equals(listaCarro.get(i).getMarca())){
                        if(nuevoCarro.getLinea().toUpperCase().equals(listaCarro.get(i).getLinea())){
                            if(nuevoCarro.getModelo().equals(listaCarro.get(i).getModelo())){
                                indexCarro = listaCarro.get(i).getIdCarro();
                            }
                        }
                    }
                }
            }
            System.out.print("" + indexCarro);

            ArrayList <Pieza> listaPieza = auxPieza.listar();
            Pieza nuevaPieza = new Pieza();
            nuevaPieza.setNumeroPieza(Integer.valueOf(NumeroPieza.getText()));
            nuevaPieza.setPrecio_compra(Float.parseFloat(PrecioCompra.getText().replace(",", ".")));
            nuevaPieza.setPrecio_venta(Float.parseFloat(PrecioVenta.getText().replace(",", ".")));
            nuevaPieza.setIdProveedor(indexProveedor);
            nuevaPieza.setIdNombrePieza(indexNombrePieza);
            nuevaPieza.setIdEstadoPieza(indexEstadoPieza);
            nuevaPieza.setIdMarcaPieza(indexMarcaPieza);
            nuevaPieza.setIdCarro(indexCarro);

            for(int i = 0; i<listaPieza.size();i++){
                if(nuevaPieza.getIdNombrePieza() == listaPieza.get(i).getIdNombrePieza()){
                    if(nuevaPieza.getNumeroPieza() == listaPieza.get(i).getNumeroPieza()){
                        if(nuevaPieza.getIdMarcaPieza() == listaPieza.get(i).getIdMarcaPieza()){
                            if(nuevaPieza.getIdEstadoPieza() == listaPieza.get(i).getIdEstadoPieza()){
                                if(nuevaPieza.getIdCarro() == listaPieza.get(i).getIdCarro()){
                                    if(nuevaPieza.getPrecio_compra() == listaPieza.get(i).getPrecio_compra()){
                                        if(nuevaPieza.getPrecio_venta() == listaPieza.get(i).getPrecio_venta()){
                                            existePieza = true;
                                            indexPieza = listaPieza.get(i).getIdPieza();
                                        }               
                                    }
                                }
                            }
                        }
                    }
                }
            }

            if(!existePieza){
                auxPieza.insertar(nuevaPieza);
                listaPieza = auxPieza.listar();
                for(int i = 0; i<listaPieza.size();i++){
                    if(nuevaPieza.getIdNombrePieza() == listaPieza.get(i).getIdNombrePieza()){
                        if(nuevaPieza.getNumeroPieza() == listaPieza.get(i).getNumeroPieza()){
                            if(nuevaPieza.getIdMarcaPieza() == listaPieza.get(i).getIdMarcaPieza()){
                                if(nuevaPieza.getIdEstadoPieza() == listaPieza.get(i).getIdEstadoPieza()){
                                    if(nuevaPieza.getIdCarro() == listaPieza.get(i).getIdCarro()){
                                        if(nuevaPieza.getPrecio_compra() == listaPieza.get(i).getPrecio_compra()){
                                            if(nuevaPieza.getPrecio_venta() == listaPieza.get(i).getPrecio_venta()){
                                                indexPieza = listaPieza.get(i).getIdPieza();
                                            }               
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            nuevoDetalle.setCantidad(cantidadCompra);
            nuevoDetalle.setIdPieza(indexPieza);
            listaDetalleFacturaCompra.add(nuevoDetalle);
            TablaIDPieza = "" + indexPieza;
            TablaPrecio = Double.parseDouble(PrecioCompra.getText().replace(",", "."));
            TablaCantidad = (Integer)Cantidad.getValue(); 
            TablaSubtotal = TablaCantidad * TablaPrecio;



            Object[] columnas = {TablaIDPieza,TablaNombrePieza,TablaPrecio,TablaCantidad,TablaMarca,TablaSubtotal};
            model.addRow(columnas);

            this.total = this.total + TablaSubtotal;

            TotalDesing.setText("TOTAL: " + (double)this.total + " Q");
            nombrePieza.setSelectedIndex(0);
            proveedor.setSelectedIndex(0);
            PrecioCompra.setText("");
            PrecioVenta.setText("");
            Cantidad.setValue(0);
            NumeroPieza.setText("");
            estado.setSelectedIndex(0);
            marcaPieza.setSelectedIndex(0);
            marca.setText("MARCA");
            linea.setText("LINEA");
            año.setText("AÑO");
            
        }else{
            Errores.setText("No puede haber campos vacios.");  
        }
        
        
        
        
        //crear el detalle de compra  
        // dejar el campo de factura del detalle en blanco
        //mostrar en tabla
        //tener el total de la compra y verificar si hay dinero sufiiente para comprar
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marcaActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed

    }//GEN-LAST:event_lineaActionPerformed

    private void lineaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_lineaCaretUpdate

    }//GEN-LAST:event_lineaCaretUpdate

    private void PrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioVentaActionPerformed

    private void NumeroPiezaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NumeroPiezaKeyTyped
        if(NumeroPieza.getText().length() == 9){
            evt.consume();
        }
    }//GEN-LAST:event_NumeroPiezaKeyTyped

    private void PrecioCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioCompraKeyTyped
        if(PrecioCompra.getText().length() == 9){
            evt.consume();
        }
    }//GEN-LAST:event_PrecioCompraKeyTyped

    private void PrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioVentaKeyTyped
        if(PrecioVenta.getText().length() == 9){
            evt.consume();
        }
    }//GEN-LAST:event_PrecioVentaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        if(!listaDetalleFacturaCompra.isEmpty()){
            CompraPiezaFrame.agregarDetalle.setEnabled(false);
            CompraPiezaFrame.realizarVenta.setEnabled(true);
            CompraPiezaFrame.totalFacturaCompra.setText("TOTAL A PAGAR: Q. "+this.total);
        }else{
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252,100,68)));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252,100,68)));
    }//GEN-LAST:event_jButton1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Detalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Detalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarMarcaPieza;
    private javax.swing.JButton AgregarNombrePieza;
    private javax.swing.JButton AgregarProveedor;
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JLabel Errores;
    private javax.swing.JFormattedTextField NumeroPieza;
    private javax.swing.JFormattedTextField PrecioCompra;
    private javax.swing.JFormattedTextField PrecioVenta;
    private javax.swing.JLabel TotalDesing;
    private javax.swing.JTextField año;
    private javax.swing.JLabel cerrar;
    public static javax.swing.JComboBox<String> estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField linea;
    private javax.swing.JTextField marca;
    public static javax.swing.JComboBox<String> marcaPieza;
    public static javax.swing.JComboBox<String> nombrePieza;
    public static javax.swing.JComboBox<String> proveedor;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
