/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import proyectobd.dao.mysql.MySQLDetalleFacturaProducto;
import proyectobd.dao.mysql.MySQLFacturaGeneral;
import proyectobd.dao.mysql.MySQLFacturaProducto;
import proyectobd.dao.mysql.MySQLProducto;
import proyectobd.dao.mysql.MySQLProveedor;
import proyectobd.modelos.DetalleFacturaCompra;
import proyectobd.modelos.DetalleFacturaProducto;
import proyectobd.modelos.Producto;
import proyectobd.modelos.Proveedor;
import static proyectobd.vistas.modulo.compraVenta.Detalle.listaDetalleFacturaCompra;
import static proyectobd.vistas.modulo.compraVenta.Detalle.proveedor;

/**
 *
 * @author ricar
 */
public class DetalleProducto extends javax.swing.JFrame {
    public static ArrayList <DetalleFacturaProducto> listaDetalleFacturaProducto = new ArrayList();
    public static float total = (float)0.00;
    /**
     * Creates new form DetalleProducto
     */
    public DetalleProducto() {
        initComponents();
        this.setLocationRelativeTo(null);
        MySQLProveedor auxProveedor = new MySQLProveedor();
        ArrayList <Proveedor> listaProveedor = auxProveedor.listar();
        for(int i = 0; i<listaProveedor.size();i++){
            Proveedor.addItem(listaProveedor.get(i).getNombre());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Proveedor = new javax.swing.JComboBox<>();
        AgregarProveedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        TotalDesing = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Cantidad = new javax.swing.JSpinner();
        jSeparator6 = new javax.swing.JSeparator();
        cerrar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Precio = new javax.swing.JFormattedTextField();
        Errores = new javax.swing.JLabel();
        Descripcion = new javax.swing.JTextField();
        Nombre = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(252, 100, 68));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 100, 68));
        jLabel1.setText("DETALLE DE COMPRA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 230, 10));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/incono_silla_mini.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        jLabel5.setBackground(new java.awt.Color(252, 100, 68));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(252, 100, 68));
        jLabel5.setText("PROVEEDOR:");
        jLabel5.setToolTipText("");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, 30));

        Proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PROVEEDOR" }));
        Proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(Proveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 150, 30));

        AgregarProveedor.setText("+");
        AgregarProveedor.setToolTipText("");
        AgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarProveedorActionPerformed(evt);
            }
        });
        jPanel1.add(AgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 50, 30));

        jLabel6.setBackground(new java.awt.Color(252, 100, 68));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(252, 100, 68));
        jLabel6.setText("NOMBRE:");
        jLabel6.setToolTipText("");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 30));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 200, 20));

        jLabel7.setBackground(new java.awt.Color(252, 100, 68));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(252, 100, 68));
        jLabel7.setText("PRECIO:");
        jLabel7.setToolTipText("");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, -1, 30));

        jSeparator3.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 200, 20));

        jLabel8.setBackground(new java.awt.Color(252, 100, 68));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 100, 68));
        jLabel8.setText("DESCRIPCION:");
        jLabel8.setToolTipText("");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 30));

        jSeparator4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 200, 20));

        jButton2.setBackground(new java.awt.Color(252, 100, 68));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("AGREGAR");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 330, 40));

        jButton1.setBackground(new java.awt.Color(252, 100, 68));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("TERMINAR");
        jButton1.setBorder(null);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 470, 420, 40));

        tabla.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tabla.setForeground(new java.awt.Color(252, 100, 68));
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Proveedor", "Precio", "Cantidad", "Subtotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(252, 100, 68));
        tabla.setSelectionBackground(new java.awt.Color(252, 100, 68));
        jScrollPane2.setViewportView(tabla);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 420, 320));

        TotalDesing.setBackground(new java.awt.Color(252, 100, 68));
        TotalDesing.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        TotalDesing.setForeground(new java.awt.Color(252, 100, 68));
        TotalDesing.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalDesing.setText("TOTAL: 0.00Q ");
        TotalDesing.setToolTipText("");
        jPanel1.add(TotalDesing, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 430, 170, 30));

        jLabel9.setBackground(new java.awt.Color(252, 100, 68));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 100, 68));
        jLabel9.setText("CANTIDAD:");
        jLabel9.setToolTipText("");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, -1, 30));

        Cantidad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Cantidad.setBorder(null);
        jPanel1.add(Cantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 200, 30));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 200, 20));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, 30));

        jLabel14.setBackground(new java.awt.Color(252, 100, 68));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(252, 100, 68));
        jLabel14.setText("Q/u");
        jLabel14.setToolTipText("");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 250, 30, 30));

        Precio.setBorder(null);
        Precio.setForeground(new java.awt.Color(252, 100, 68));
        Precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        Precio.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        Precio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioKeyTyped(evt);
            }
        });
        jPanel1.add(Precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 160, 30));
        jPanel1.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 1020, -1));

        Descripcion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Descripcion.setForeground(new java.awt.Color(252, 100, 68));
        Descripcion.setBorder(null);
        jPanel1.add(Descripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 30));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(252, 100, 68));
        Nombre.setBorder(null);
        jPanel1.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 200, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ProveedorActionPerformed

    private void AgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarProveedorActionPerformed
        Agregar.tipo = 2;
        Agregar append = new Agregar();
        append.setVisible(true);
    }//GEN-LAST:event_AgregarProveedorActionPerformed

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252,100,68)));
    }//GEN-LAST:event_jButton2MouseExited
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        DetalleFacturaCompra nuevoDetalle = new DetalleFacturaCompra();
        DefaultTableModel model = (DefaultTableModel)tabla.getModel();
        
        MySQLProveedor auxProveedor = new MySQLProveedor();
        MySQLProducto auxProducto = new MySQLProducto();
        MySQLDetalleFacturaProducto auxDetalleFacturaProducto = new MySQLDetalleFacturaProducto();
        MySQLFacturaProducto auxFacturaProducto = new MySQLFacturaProducto();
        MySQLFacturaGeneral auxFacturaGeneral = new MySQLFacturaGeneral();
                
        ArrayList <Proveedor> listaProveedor  = auxProveedor.listar();
        ArrayList <Producto> listaProducto  = auxProducto.listar();
        
        Producto producto = new Producto();
        DetalleFacturaProducto detalleFacturaProducto = new DetalleFacturaProducto();
        
        boolean vacio1 = Nombre.getText().equals("");
        boolean vacio2 = (Proveedor.getSelectedIndex() == 0);
        boolean vacio3 = Precio.getText().equals("");
        boolean vacio4 = Descripcion.getText().equals("");
        boolean vacio5 = ((Integer)Cantidad.getValue() <= 0);
        boolean existeProducto = false;
        
        if(!vacio1 && !vacio2 && !vacio3 && !vacio4 && !vacio5){
            String nombre = Nombre.getText();
            int indexProveedor = 0;
            double precio = Double.parseDouble(Precio.getText().replace(",", "."));
            String descripcion = Descripcion.getText();
            int cantidad = (Integer)Cantidad.getValue();
            int indexProducto = 0;
            for(int i = 0; i < listaProveedor.size(); i++){
                if(Proveedor.getSelectedItem().equals(listaProveedor.get(i).getNombre())){
                    indexProveedor = listaProveedor.get(i).getIdProveedor();
                }
            }
            producto.setNombre(nombre);
            producto.setIdProveedor(indexProveedor);
            producto.setPrecio((float)precio);
            producto.setDescripcion(descripcion);
            for(int i = 0; i<listaProducto.size();i++){
                if(producto.getNombre().toUpperCase().equals(listaProducto.get(i).getNombre())){
                    if(producto.getIdProveedor() == (listaProducto.get(i).getIdProveedor())){
                        if(producto.getPrecio() == listaProducto.get(i).getPrecio()){
                            if(producto.getDescripcion().toUpperCase().equals(listaProducto.get(i).getDescripcion())){
                                existeProducto = true;
                                indexProducto = listaProducto.get(i).getIdProducto();
                            }
                        }
                    }
                }
            }
            if(!existeProducto){
                auxProducto.insertar(producto);
                listaProducto  = auxProducto.listar();
                for(int i = 0; i<listaProducto.size();i++){
                    if(producto.getNombre().toUpperCase().equals(listaProducto.get(i).getNombre())){
                        if(producto.getIdProveedor() == (listaProducto.get(i).getIdProveedor())){
                            if(producto.getPrecio() == listaProducto.get(i).getPrecio()){
                                if(producto.getDescripcion().toUpperCase().equals(listaProducto.get(i).getDescripcion())){
                                    existeProducto = true;
                                    indexProducto = listaProducto.get(i).getIdProducto();
                                }
                            }
                        }
                    }
                }
            }
            int a;
            detalleFacturaProducto.setCantidad(cantidad);
            detalleFacturaProducto.setIdProducto(indexProducto);
            listaDetalleFacturaProducto.add(detalleFacturaProducto);
            
            Object[] columnas = {nombre,Proveedor.getSelectedItem(),precio,cantidad,precio*cantidad};
            model.addRow(columnas);
            
            Nombre.setText("");
            Proveedor.setSelectedIndex(0);
            Precio.setText("");
            Descripcion.setText("");
            Cantidad.setValue(0);
            
            this.total = this.total + (float)(precio*cantidad);
            
            TotalDesing.setText("TOTAL: "+ this.total + " Q.");
            
            
        }else{
            Errores.setText("No puede haber campos vacios.");  
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0,0,0)));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252,100,68)));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        if(!listaDetalleFacturaProducto.isEmpty()){
            CompraObjetoFrame.agregarDetalle.setEnabled(false);
            CompraObjetoFrame.realizarCompra.setEnabled(true);
            CompraObjetoFrame.totalFacturaProducto.setText("TOTAL A PAGAR: Q. "+this.total);
        }else{
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    private void PrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioKeyTyped
        if(Precio.getText().length() == 9){
            evt.consume();
        }
    }//GEN-LAST:event_PrecioKeyTyped

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarProveedor;
    private javax.swing.JSpinner Cantidad;
    private javax.swing.JTextField Descripcion;
    private javax.swing.JLabel Errores;
    private javax.swing.JTextField Nombre;
    private javax.swing.JFormattedTextField Precio;
    public static javax.swing.JComboBox<String> Proveedor;
    private javax.swing.JLabel TotalDesing;
    private javax.swing.JLabel cerrar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
