/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import proyectobd.dao.mysql.MySQLDetalleFacturaCompra;
import proyectobd.dao.mysql.MySQLDetalleFacturaExtraordinaria;
import proyectobd.dao.mysql.MySQLDetalleFacturaProducto;
import proyectobd.dao.mysql.MySQLFacturaGeneral;
import proyectobd.modelos.DetalleFacturaCompra;
import proyectobd.modelos.DetalleFacturaExtraordinaria;
import proyectobd.modelos.DetalleFacturaProducto;
import proyectobd.modelos.FacturaGeneral;

/**
 *
 * @author ricar
 */
public class DetalleConsulta extends javax.swing.JFrame {
    public static int IdFactura = 0;
    
    /**
     * Creates new form DetalleConsulta
     */
    public DetalleConsulta() {
        initComponents();
        DefaultTableModel model = (DefaultTableModel)tabla.getModel();
        this.setLocationRelativeTo(null);
        
        MySQLFacturaGeneral auxFacturaGeneral = new MySQLFacturaGeneral();
        MySQLDetalleFacturaCompra auxDetalleFacturaCompra = new MySQLDetalleFacturaCompra();
        
        MySQLDetalleFacturaExtraordinaria auxDetalleFacturaExtraordinaria = new MySQLDetalleFacturaExtraordinaria();
        
        MySQLDetalleFacturaProducto auxDetalleFacturaProducto = new MySQLDetalleFacturaProducto();
        
        ArrayList <FacturaGeneral> listaFacturaGeneral = auxFacturaGeneral.listar();
        ArrayList <DetalleFacturaCompra> listaDetalleFacturaCompra = auxDetalleFacturaCompra.listar();
        
        ArrayList <DetalleFacturaExtraordinaria> listaDetalleFacturaExtraordinaria = auxDetalleFacturaExtraordinaria.listar();
        
        ArrayList <DetalleFacturaProducto> listaDetalleFacturaProducto = auxDetalleFacturaProducto.listar();
        
        
        boolean esCompra = false;
        int es = 0;
        
        for(int i = 0; i<listaFacturaGeneral.size(); i++){
            if(listaFacturaGeneral.get(i).getIdFacturaGeneral() == IdFactura){
                switch(listaFacturaGeneral.get(i).getIdTipoFactura()){
                    case 2://Compra
                        model.setColumnIdentifiers(new String[]{"IdFacturaCompra","IdPieza","Cantidad","IdFacturaGeneral"});
                        esCompra = true;
                        es = 2;
                        break;
                    case 4://Extra
                        model.setColumnIdentifiers(new String[]{"IdDetalleExtraordinario","Descripcion","Cantidad","IdFacturaGeneral"});
                        esCompra = true;
                        es = 4;
                        break;
                    case 5://producto
                        model.setColumnIdentifiers(new String[]{"IdFacturaProducto","IdProducto","Cantidad","IdFacturaGeneral"});
                        esCompra = true;
                        es = 5;
                        break;
                    default:
                        break;
                }
            }
        }
        
        if(esCompra){
            switch(es){
                case 2:
                    for(int i = 0; i < listaDetalleFacturaCompra.size();i++){
                        model.addRow(new String[]{""+listaDetalleFacturaCompra.get(i).getIdFacturaCompra(),""+listaDetalleFacturaCompra.get(i).getIdPieza(),""+listaDetalleFacturaCompra.get(i).getCantidad(),""+IdFactura});
                    }
                    break;
                case 4:
                    for(int i = 0; i < listaDetalleFacturaExtraordinaria.size();i++){
                        model.addRow(new String[]{""+listaDetalleFacturaExtraordinaria.get(i).getIdDetalleFacturaExtraordinaria(),""+listaDetalleFacturaExtraordinaria.get(i).getDescripcion(),""+listaDetalleFacturaExtraordinaria.get(i).getCantidad(),""+IdFactura});
                    }
                    break;
                case 5:
                    for(int i = 0; i < listaDetalleFacturaProducto.size();i++){
                        model.addRow(new String[]{""+listaDetalleFacturaProducto.get(i).getIdFacturaProducto(),""+listaDetalleFacturaProducto.get(i).getIdProducto(),""+listaDetalleFacturaProducto.get(i).getCantidad(),""+IdFactura});
                    }
                    break;
                default:
                    break;
            }
        }else{
            model.addRow(new String[] {"ID invalido","ID invalido","ID invalido","ID invalido"});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cerrar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel1.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 10, -1, 30));

        jLabel1.setBackground(new java.awt.Color(252, 100, 68));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(252, 100, 68));
        jLabel1.setText("DETALLE DE CONSULTA");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_lista_mini.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        jSeparator1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 250, 10));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "N/A", "N/A", "N/A", "N/A"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setGridColor(new java.awt.Color(252, 100, 68));
        jScrollPane1.setViewportView(tabla);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 670, 330));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 557, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose();
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalleConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalleConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalleConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalleConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalleConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
