/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import proyectobd.controladores.ControladorHorario;
import proyectobd.dao.mysql.MySQLAsistencia;
import proyectobd.dao.mysql.MySQLInasistencia;
import proyectobd.excepciones.Excepcion;
import proyectobd.modelos.Asistencia;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.Horario;
import proyectobd.modelos.Inasistencia;
import proyectobd.vistas.Login;

/**
 *
 * @author ricar
 */
public class Venta extends javax.swing.JFrame {
    private ControladorHorario controladorHorario;
    public static Empleado info;
    public static String regreso;

    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        controladorHorario = new ControladorHorario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CompraFondo = new javax.swing.JPanel();
        VentaPieza = new javax.swing.JLabel();
        VentaLista = new javax.swing.JLabel();
        name_pieza = new javax.swing.JLabel();
        name_consulta = new javax.swing.JLabel();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        Errores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        CompraFondo.setBackground(new java.awt.Color(255, 255, 255));
        CompraFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        CompraFondo.setPreferredSize(new java.awt.Dimension(1050, 575));
        CompraFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VentaPieza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentaPieza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_pieza.png"))); // NOI18N
        VentaPieza.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VentaPieza.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VentaPiezaMouseMoved(evt);
            }
        });
        VentaPieza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaPiezaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentaPiezaMouseExited(evt);
            }
        });
        CompraFondo.add(VentaPieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 200, 200));

        VentaLista.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        VentaLista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_lista.png"))); // NOI18N
        VentaLista.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        VentaLista.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                VentaListaMouseMoved(evt);
            }
        });
        VentaLista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VentaListaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VentaListaMouseExited(evt);
            }
        });
        CompraFondo.add(VentaLista, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 200, 200));

        name_pieza.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_pieza.setForeground(new java.awt.Color(252, 100, 68));
        name_pieza.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_pieza.setText("PIEZA");
        CompraFondo.add(name_pieza, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 200, -1));

        name_consulta.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        name_consulta.setForeground(new java.awt.Color(252, 100, 68));
        name_consulta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name_consulta.setText("CONSULTA");
        CompraFondo.add(name_consulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, 200, -1));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        CompraFondo.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, 30));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        CompraFondo.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 10, -1, 30));
        CompraFondo.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 1020, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1050, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CompraFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(CompraFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VentaPiezaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaPiezaMouseMoved
        VentaPieza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 100, 68)));
    }//GEN-LAST:event_VentaPiezaMouseMoved

    private void VentaPiezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaPiezaMouseClicked
        this.dispose();
        VentaPiezaFrame.info = info;
        VentaPiezaFrame venta = new VentaPiezaFrame();
        venta.setVisible(true);
    }//GEN-LAST:event_VentaPiezaMouseClicked

    private void VentaPiezaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaPiezaMouseExited
        VentaPieza.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_VentaPiezaMouseExited

    private void VentaListaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaListaMouseMoved
        VentaLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 100, 68)));
    }//GEN-LAST:event_VentaListaMouseMoved

    private void VentaListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaListaMouseClicked
        ConsultaVentaFrame consulta = new ConsultaVentaFrame();
        dispose();
        consulta.setVisible(true);
    }//GEN-LAST:event_VentaListaMouseClicked

    private void VentaListaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VentaListaMouseExited
        VentaLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
    }//GEN-LAST:event_VentaListaMouseExited

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        Horario horario = controladorHorario.obtenerHorario(info.getIdHorario());

        if (horario != null) {
            Calendar calendario = Calendar.getInstance();
            String horaActual = calendario.get(Calendar.HOUR_OF_DAY) + ":" + calendario.get(Calendar.MINUTE) + ":" + calendario.get(Calendar.SECOND);

            try {
                DateFormat dateFormat = new SimpleDateFormat("hh:mm");

                Date DHoraSalida = dateFormat.parse(horario.getSalida());
                Date DHoraActual = dateFormat.parse(horaActual);

                if (DHoraSalida.compareTo(DHoraActual) > 0) {
                    int respuesta = JOptionPane.showConfirmDialog(null, "Tu hora de salida es: " + horario.getSalida() + ". Estas seguro que deseas salir? (se te contara como inasistencia)", "Cerrando Sesion", JOptionPane.YES_NO_OPTION);
                    if (respuesta == 0) {
                        try {
                            Inasistencia inasistencia = new Inasistencia();
                            inasistencia.setIdEmpleado(info.getIdEmpleado());
                            inasistencia.setIdTipoInasistencia(2);

                            MySQLInasistencia myinasistencia = new MySQLInasistencia();
                            myinasistencia.insertar(inasistencia);

                            MySQLAsistencia myasistencia = new MySQLAsistencia();
                            Asistencia aux = myasistencia.obtenerIdyFecha(info.getIdEmpleado());
                            aux.setHora_salida(horaActual);
                            myasistencia.modificar(aux);
                            JOptionPane.showMessageDialog(null, "Cerro Sesion correctamente");
                            dispose();
                            Login login = new Login();
                            login.setVisible(true);
                        } catch (Excepcion e) {
                            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            System.exit(0);
                        }
                    }
                } else {
                    MySQLAsistencia myasistencia = new MySQLAsistencia();
                    Asistencia aux = myasistencia.obtenerIdyFecha(info.getIdEmpleado());
                    aux.setHora_salida(horaActual);
                    myasistencia.modificar(aux);
                    JOptionPane.showMessageDialog(null, "Cerro Sesion correctamente");
                    dispose();
                    Login login = new Login();
                    login.setVisible(true);
                }

            } catch (ParseException ex) {
                Logger.getLogger(Venta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(Compra.ICONIFIED);
    }//GEN-LAST:event_minimizarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CompraFondo;
    public static javax.swing.JLabel Errores;
    private javax.swing.JLabel VentaLista;
    private javax.swing.JLabel VentaPieza;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel minimizar;
    private javax.swing.JLabel name_consulta;
    private javax.swing.JLabel name_pieza;
    // End of variables declaration//GEN-END:variables
}
