/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.compraVenta;

import java.util.ArrayList;
import java.util.Calendar;
import proyectobd.controladores.ControladorPersona;
import proyectobd.dao.mysql.MySQLDetalleFacturaVenta;
import proyectobd.dao.mysql.MySQLEmpresa;
import proyectobd.dao.mysql.MySQLFacturaGeneral;
import proyectobd.dao.mysql.MySQLFacturaVenta;
import proyectobd.dao.mysql.MySQLMovimientoFinanciero;
import proyectobd.dao.mysql.MySQLPersona;
import proyectobd.dao.mysql.MySQLTipoPago;
import proyectobd.modelos.DetalleFacturaVenta;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.Empresa;
import proyectobd.modelos.FacturaGeneral;
import proyectobd.modelos.FacturaVenta;
import proyectobd.modelos.MovimientoFinanciero;
import proyectobd.modelos.Persona;
import proyectobd.modelos.TipoPago;

/**
 *
 * @author ricar
 */
public class VentaPiezaFrame extends javax.swing.JFrame {

    public static Empleado info;

    /**
     * Creates new form VentaPiezaFrame
     */
    public VentaPiezaFrame() {
        initComponents();
        this.setLocationRelativeTo(null);

        this.empleado.setText(new ControladorPersona().obtenerPorID(info.getIdPersona()).getNombre());

        this.idEmpleado.setText(String.valueOf(info.getIdEmpleado()));

        Calendar c = Calendar.getInstance();
        int mes = c.get(Calendar.MONTH) + 1;
        int dia = c.get(Calendar.DAY_OF_MONTH);
        int año = c.get(Calendar.YEAR);
        String fecha = dia + "/" + mes + "/" + año;
        this.fecha.setText(fecha.toString());

        MySQLEmpresa aux3 = new MySQLEmpresa();
        MySQLTipoPago aux4 = new MySQLTipoPago();

        ArrayList<Empresa> listaEmpresa = aux3.listar();
        ArrayList<TipoPago> listaTipoPago = aux4.listar();

        for (int i = 0; i < listaEmpresa.size(); i++) {
            empresa.addItem(listaEmpresa.get(i).getNombre());
        }
        for (int i = 0; i < listaTipoPago.size(); i++) {
            tipoPago.addItem(listaTipoPago.get(i).getTipo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        totalDesign = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        empleado = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        idEmpleado = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tipoPago = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        empresa = new javax.swing.JComboBox<>();
        AgregarEmpresa = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        agregarDetalle = new javax.swing.JButton();
        fecha = new javax.swing.JLabel();
        realizarVenta = new javax.swing.JButton();
        cerrar = new javax.swing.JLabel();
        minimizar = new javax.swing.JLabel();
        regresar2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Nit = new javax.swing.JTextField();
        Errores = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Nombre = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel15 = new javax.swing.JLabel();
        Apellido = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        DPI = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        Direccion = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_pieza_mini.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 30, 30));

        totalDesign.setBackground(new java.awt.Color(252, 100, 68));
        totalDesign.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        totalDesign.setForeground(new java.awt.Color(252, 100, 68));
        totalDesign.setText("TOTAL:  0.00 Q");
        jPanel3.add(totalDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, 30));

        jSeparator1.setForeground(new java.awt.Color(108, 108, 108));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 220, 10));

        empleado.setBackground(new java.awt.Color(252, 100, 68));
        empleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        empleado.setForeground(new java.awt.Color(252, 100, 68));
        empleado.setText("EMPLEADO X1");
        jPanel3.add(empleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 600, 30));

        jLabel8.setBackground(new java.awt.Color(252, 100, 68));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(252, 100, 68));
        jLabel8.setText("EMPLEADO:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 110, 30));

        jLabel11.setBackground(new java.awt.Color(252, 100, 68));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(252, 100, 68));
        jLabel11.setText("ID EMPLEADO:");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 30));

        idEmpleado.setBackground(new java.awt.Color(252, 100, 68));
        idEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idEmpleado.setForeground(new java.awt.Color(252, 100, 68));
        idEmpleado.setText("1");
        jPanel3.add(idEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 200, 30));

        jLabel9.setBackground(new java.awt.Color(252, 100, 68));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(252, 100, 68));
        jLabel9.setText("NOMBRE:");
        jLabel9.setToolTipText("");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 100, 30));

        tipoPago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TIPO DE PAGO" }));
        tipoPago.setEnabled(false);
        tipoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoPagoActionPerformed(evt);
            }
        });
        jPanel3.add(tipoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 200, 30));

        jLabel10.setBackground(new java.awt.Color(252, 100, 68));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(252, 100, 68));
        jLabel10.setText("EMPRESA:");
        jLabel10.setToolTipText("");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, 30));

        empresa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EMPRESA" }));
        empresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empresaActionPerformed(evt);
            }
        });
        jPanel3.add(empresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 150, 30));

        AgregarEmpresa.setText("+");
        AgregarEmpresa.setToolTipText("");
        AgregarEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarEmpresaActionPerformed(evt);
            }
        });
        jPanel3.add(AgregarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 50, 30));

        jLabel12.setBackground(new java.awt.Color(252, 100, 68));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(252, 100, 68));
        jLabel12.setText("FECHA:");
        jLabel12.setToolTipText("");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, -1, 30));

        agregarDetalle.setBackground(new java.awt.Color(252, 100, 68));
        agregarDetalle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregarDetalle.setText("AGREGAR DETALLE");
        agregarDetalle.setBorder(null);
        agregarDetalle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregarDetalle.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                agregarDetalleMouseMoved(evt);
            }
        });
        agregarDetalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                agregarDetalleMouseExited(evt);
            }
        });
        agregarDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarDetalleActionPerformed(evt);
            }
        });
        jPanel3.add(agregarDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 180, 50));

        fecha.setBackground(new java.awt.Color(252, 100, 68));
        fecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fecha.setForeground(new java.awt.Color(252, 100, 68));
        fecha.setToolTipText("");
        jPanel3.add(fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 200, 30));

        realizarVenta.setBackground(new java.awt.Color(252, 100, 68));
        realizarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        realizarVenta.setText("REALIZAR VENTA");
        realizarVenta.setBorder(null);
        realizarVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        realizarVenta.setEnabled(false);
        realizarVenta.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                realizarVentaMouseMoved(evt);
            }
        });
        realizarVenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                realizarVentaMouseExited(evt);
            }
        });
        realizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                realizarVentaActionPerformed(evt);
            }
        });
        jPanel3.add(realizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 180, 50));

        cerrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });
        jPanel3.add(cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, -1, 30));

        minimizar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        minimizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizarMouseClicked(evt);
            }
        });
        jPanel3.add(minimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, 30));

        regresar2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        regresar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_regreso_32px.png"))); // NOI18N
        regresar2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        regresar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                regresar2MouseClicked(evt);
            }
        });
        jPanel3.add(regresar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, -1, 30));

        jLabel13.setBackground(new java.awt.Color(252, 100, 68));
        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(252, 100, 68));
        jLabel13.setText("TIPO DE PAGO:");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, -1, 30));

        Nit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nit.setForeground(new java.awt.Color(252, 100, 68));
        Nit.setBorder(null);
        Nit.setEnabled(false);
        Nit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NitFocusLost(evt);
            }
        });
        Nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NitActionPerformed(evt);
            }
        });
        Nit.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NitKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                NitKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NitKeyTyped(evt);
            }
        });
        jPanel3.add(Nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 200, 30));
        jPanel3.add(Errores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1030, 20));

        jLabel14.setBackground(new java.awt.Color(252, 100, 68));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(252, 100, 68));
        jLabel14.setText("NIT:");
        jLabel14.setToolTipText("");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 100, 30));

        Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Nombre.setForeground(new java.awt.Color(252, 100, 68));
        Nombre.setBorder(null);
        Nombre.setEnabled(false);
        Nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                NombreFocusLost(evt);
            }
        });
        Nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                NombreKeyTyped(evt);
            }
        });
        jPanel3.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 200, 30));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 320, -1));
        jPanel3.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 332, 320, -1));

        jLabel15.setBackground(new java.awt.Color(252, 100, 68));
        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(252, 100, 68));
        jLabel15.setText("APELLIDO:");
        jLabel15.setToolTipText("");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, 30));

        Apellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Apellido.setForeground(new java.awt.Color(252, 100, 68));
        Apellido.setBorder(null);
        Apellido.setEnabled(false);
        Apellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ApellidoFocusLost(evt);
            }
        });
        Apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ApellidoKeyTyped(evt);
            }
        });
        jPanel3.add(Apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 200, 30));
        jPanel3.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 320, -1));

        jLabel16.setBackground(new java.awt.Color(252, 100, 68));
        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(252, 100, 68));
        jLabel16.setText("DPI:");
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 100, 30));

        DPI.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        DPI.setForeground(new java.awt.Color(252, 100, 68));
        DPI.setBorder(null);
        DPI.setEnabled(false);
        DPI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DPIFocusLost(evt);
            }
        });
        DPI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DPIKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DPIKeyTyped(evt);
            }
        });
        jPanel3.add(DPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 200, 30));
        jPanel3.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, 320, -1));

        jLabel17.setBackground(new java.awt.Color(252, 100, 68));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(252, 100, 68));
        jLabel17.setText("DIRECCION:");
        jLabel17.setToolTipText("");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 100, 30));

        Direccion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Direccion.setForeground(new java.awt.Color(252, 100, 68));
        Direccion.setBorder(null);
        Direccion.setEnabled(false);
        Direccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                DireccionFocusLost(evt);
            }
        });
        Direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                DireccionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                DireccionKeyTyped(evt);
            }
        });
        jPanel3.add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 200, 30));
        jPanel3.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 490, 320, -1));

        jLabel3.setBackground(new java.awt.Color(252, 100, 68));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(252, 100, 68));
        jLabel3.setText("VENTA DE PIEZA");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoPagoActionPerformed

    private void empresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empresaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_empresaActionPerformed

    private void AgregarEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarEmpresaActionPerformed
        Agregar.tipo = 3;
        Agregar append = new Agregar();
        append.setVisible(true);
    }//GEN-LAST:event_AgregarEmpresaActionPerformed

    private void agregarDetalleMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarDetalleMouseMoved
        agregarDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_agregarDetalleMouseMoved

    private void agregarDetalleMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarDetalleMouseExited
        agregarDetalle.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 100, 68)));
    }//GEN-LAST:event_agregarDetalleMouseExited

    private void agregarDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarDetalleActionPerformed
        boolean vacio = empresa.getSelectedIndex() == 0;
        Errores.setText("");
        if (!vacio) {
            DetalleVentaPieza detalle = new DetalleVentaPieza();
            detalle.setVisible(true);
        } else {
            Errores.setText("No puede haber campos vacios.");
        }
    }//GEN-LAST:event_agregarDetalleActionPerformed

    private void realizarVentaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaMouseMoved
        realizarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    }//GEN-LAST:event_realizarVentaMouseMoved

    private void realizarVentaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_realizarVentaMouseExited
        realizarVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(252, 100, 68)));
    }//GEN-LAST:event_realizarVentaMouseExited

    private void realizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_realizarVentaActionPerformed
        MySQLPersona auxPersona = new MySQLPersona();
        MySQLFacturaGeneral auxFacturaGeneral = new MySQLFacturaGeneral();
        MySQLFacturaVenta auxFacturaVenta = new MySQLFacturaVenta();
        MySQLDetalleFacturaVenta auxDetalleFacturaVenta = new MySQLDetalleFacturaVenta();
        MySQLEmpresa auxEmpresa = new MySQLEmpresa();
        MySQLTipoPago auxTipoPago = new MySQLTipoPago();
        MySQLMovimientoFinanciero auxMovimientoFinanciero = new MySQLMovimientoFinanciero();
        MovimientoFinanciero nuevoMovimiento = new MovimientoFinanciero();
        MovimientoFinanciero ultimoMovimiento = new MovimientoFinanciero();

        FacturaGeneral facturaGeneral = new FacturaGeneral();
        FacturaVenta facturaVenta = new FacturaVenta();
        DetalleFacturaVenta detalleFacturaVenta = new DetalleFacturaVenta();

        boolean ExistePersona = false;
        int IndexPersona = 0;
        int IndexEmpresa = 0;
        int IndexPago = 0;
        int IndexFacturaGeneral = 0;
        int IndexFacturaVenta = 0;
        ArrayList<Persona> listaPersona = auxPersona.listar();
        ArrayList<Empresa> listaEmpresa = auxEmpresa.listar();
        ArrayList<TipoPago> listaTipoPago = auxTipoPago.listar();
        ArrayList<FacturaGeneral> listaFacturaGeneral = auxFacturaGeneral.listar();
        ArrayList<MovimientoFinanciero> listaMovimiento = auxMovimientoFinanciero.listar();

        for (int i = 0; i < listaMovimiento.size(); i++) {
            ultimoMovimiento = listaMovimiento.get(i);
        }

        Persona persona = new Persona();

        boolean v1 = Nombre.getText().equals("");
        boolean v2 = Apellido.getText().equals("");
        boolean v3 = Direccion.getText().equals("");
        boolean v4 = DPI.getText().equals("");
        boolean v5 = Nit.getText().equals("");
        boolean v6 = tipoPago.getSelectedIndex() == 0;

        if (!v1 && !v2 && !v3 && !v4 && !v5 && !v6) {
            for (int i = 0; i < listaPersona.size(); i++) {
                if (Nit.getText().equals(listaPersona.get(i).getNit())) {
                    ExistePersona = true;
                    IndexPersona = listaPersona.get(i).getIdPersona();
                }
            }
            if (!ExistePersona) {
                persona.setApellido(Apellido.getText());
                persona.setDireccion(Direccion.getText());
                persona.setDpi(DPI.getText());
                persona.setNit(Nit.getText());
                persona.setNombre(Nombre.getText());
                auxPersona.insertar(persona);
                IndexPersona = listaPersona.size() + 1;
            }

            for (int i = 0; i < listaEmpresa.size(); i++) {
                if (listaEmpresa.get(i).getNombre().equals(empresa.getSelectedItem())) {
                    IndexEmpresa = listaEmpresa.get(i).getIdEmpresa();
                }
            }
            for (int i = 0; i < listaTipoPago.size(); i++) {
                if (listaTipoPago.get(i).getTipo().equals(tipoPago.getSelectedItem())) {
                    IndexPago = listaTipoPago.get(i).getIdTipoPago();
                }
            }

            facturaGeneral.setTotal(DetalleVentaPieza.total);
            facturaGeneral.setIdEmpleado(Integer.parseInt(idEmpleado.getText()));
            facturaGeneral.setIdEmpresa(IndexEmpresa);
            facturaGeneral.setIdTipoFactura(1);
            facturaGeneral.setIdTipoPago(IndexPago);
            auxFacturaGeneral.insertar(facturaGeneral);

            listaFacturaGeneral = auxFacturaGeneral.listar();

            for (int i = 0; i < listaFacturaGeneral.size(); i++) {
                if (listaFacturaGeneral.get(i).getTotal() == (facturaGeneral.getTotal())) {
                    if (listaFacturaGeneral.get(i).getIdEmpresa() == (facturaGeneral.getIdEmpresa())) {
                        if (listaFacturaGeneral.get(i).getIdTipoFactura() == (facturaGeneral.getIdTipoFactura())) {
                            if (listaFacturaGeneral.get(i).getIdEmpleado() == (facturaGeneral.getIdEmpleado())) {
                                if (listaFacturaGeneral.get(i).getIdTipoPago() == (facturaGeneral.getIdTipoPago())) {
                                    IndexFacturaGeneral = listaFacturaGeneral.get(i).getIdFacturaGeneral();
                                }
                            }
                        }
                    }
                }
            }
            facturaVenta.setIdPersona(IndexPersona);
            facturaVenta.setIdFacturaGeneral(IndexFacturaGeneral);
            auxFacturaVenta.insertar(facturaVenta);

            ArrayList<FacturaVenta> listaFacturaVenta = auxFacturaVenta.listar();

            IndexFacturaVenta = listaFacturaVenta.size();

            for (int i = 0; i < DetalleVentaPieza.listaDetalleFacturaVenta.size(); i++) {
                DetalleVentaPieza.listaDetalleFacturaVenta.get(i).setIdFacturaVenta(IndexFacturaVenta);
                auxDetalleFacturaVenta.insertar(DetalleVentaPieza.listaDetalleFacturaVenta.get(i));
            }

            nuevoMovimiento.setIdTipoTransaccion(1);
            nuevoMovimiento.setMonto(DetalleVentaPieza.total);
            nuevoMovimiento.setTotal(ultimoMovimiento.getTotal() - nuevoMovimiento.getMonto());
            auxMovimientoFinanciero.insertar(nuevoMovimiento);
            dispose();
            Venta venta = new Venta();
            venta.setVisible(true);
            venta.Errores.setText("VENTA EXITOSA");
        } else {
            Errores.setText("No puede dejar espacios vacios");
        }
    }//GEN-LAST:event_realizarVentaActionPerformed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        dispose(); // regresar // cerrar
        VentaPiezaFrame.info = info;
        Venta venta = new Venta();
        venta.setVisible(true);

    }//GEN-LAST:event_cerrarMouseClicked

    private void minimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizarMouseClicked
        this.setState(CompraPiezaFrame.ICONIFIED); // minimizar
    }//GEN-LAST:event_minimizarMouseClicked

    private void regresar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_regresar2MouseClicked
        dispose(); // regresar
        VentaPiezaFrame.info = info;
        Venta venta = new Venta();
        venta.setVisible(true);

    }//GEN-LAST:event_regresar2MouseClicked

    private void NitKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NitKeyTyped

    }//GEN-LAST:event_NitKeyTyped

    private void NitKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NitKeyPressed
        int indexPersona = 0;
        MySQLPersona auxPersona = new MySQLPersona();
        ArrayList<Persona> listaPersona = auxPersona.listar();
        for (int i = 0; i < listaPersona.size(); i++) {
            if (Nit.getText().equals(listaPersona.get(i).getNit())) {
                Nombre.setText(listaPersona.get(i).getNombre());
                Apellido.setText(listaPersona.get(i).getApellido());
                DPI.setText(listaPersona.get(i).getDpi());
                Direccion.setText(listaPersona.get(i).getDireccion());
                indexPersona = listaPersona.get(i).getIdPersona();
            }
        }
    }//GEN-LAST:event_NitKeyPressed

    private void NitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NitFocusLost

    }//GEN-LAST:event_NitFocusLost

    private void NombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_NombreFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFocusLost

    private void NombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreKeyPressed

    private void NombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreKeyTyped

    private void ApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ApellidoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoFocusLost

    private void ApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoKeyPressed

    private void ApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ApellidoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_ApellidoKeyTyped

    private void DPIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DPIFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DPIFocusLost

    private void DPIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DPIKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DPIKeyPressed

    private void DPIKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DPIKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DPIKeyTyped

    private void DireccionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DireccionFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionFocusLost

    private void DireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionKeyPressed

    private void DireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_DireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionKeyTyped

    private void NitKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NitKeyReleased

    }//GEN-LAST:event_NitKeyReleased

    private void NitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaPiezaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaPiezaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaPiezaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaPiezaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaPiezaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarEmpresa;
    public static javax.swing.JTextField Apellido;
    public static javax.swing.JTextField DPI;
    public static javax.swing.JTextField Direccion;
    private javax.swing.JLabel Errores;
    public static javax.swing.JTextField Nit;
    public static javax.swing.JTextField Nombre;
    public static javax.swing.JButton agregarDetalle;
    private javax.swing.JLabel cerrar;
    private javax.swing.JLabel empleado;
    public static javax.swing.JComboBox<String> empresa;
    private javax.swing.JLabel fecha;
    private javax.swing.JLabel idEmpleado;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel minimizar;
    public static javax.swing.JButton realizarVenta;
    private javax.swing.JLabel regresar2;
    public static javax.swing.JComboBox<String> tipoPago;
    public static transient javax.swing.JLabel totalDesign;
    // End of variables declaration//GEN-END:variables
}
