/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.pagos;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import proyectobd.dao.mysql.MySQLConsultas;
import proyectobd.dao.mysql.MySQLDetallePago;
import proyectobd.dao.mysql.MySQLEmpleado;
import proyectobd.dao.mysql.MySQLMovimientoFinanciero;
import proyectobd.dao.mysql.MySQLPago;
import proyectobd.modelos.DetallePago;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.MovimientoFinanciero;
import proyectobd.modelos.Pago;

/**
 *
 * @author israe
 */
public class CrearPago extends javax.swing.JFrame {

    ArrayList<DetallePago> listaDetalle;

    /**
     * Creates new form CrearPago
     */
    public CrearPago() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.listaDetalle = new ArrayList();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jTFIdEmpleado = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel46 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFMonto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel20 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTFDetalle = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 50));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setBackground(new java.awt.Color(238, 112, 82));
        jLabel45.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(238, 112, 82));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Agregar Detalle");
        jPanel1.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 370, -1));

        jTFIdEmpleado.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFIdEmpleado.setBorder(null);
        jTFIdEmpleado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFIdEmpleadoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 70, 40));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, -1, -1));

        jLabel15.setBackground(new java.awt.Color(238, 112, 82));
        jLabel15.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(238, 112, 82));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("ID Empleado");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 120, 30));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 120, 10));

        jLabel46.setBackground(new java.awt.Color(238, 112, 82));
        jLabel46.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(238, 112, 82));
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("Realizar Pago a");
        jPanel1.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 230, -1));

        jLabel16.setBackground(new java.awt.Color(238, 112, 82));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Monto");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 120, 30));

        jTFMonto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFMonto.setBorder(null);
        jTFMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFMontoKeyTyped(evt);
            }
        });
        jPanel1.add(jTFMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 70, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 120, 10));

        jLabel20.setBackground(new java.awt.Color(238, 112, 82));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 112, 82));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Detalle");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 310, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, -1, -1));

        jTFDetalle.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFDetalle.setBorder(null);
        jTFDetalle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDetalleKeyTyped(evt);
            }
        });
        jPanel1.add(jTFDetalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 260, 40));

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 310, 10));

        jButton9.setBackground(new java.awt.Color(238, 112, 82));
        jButton9.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Realizar Pago");
        jButton9.setBorder(null);
        jButton9.setFocusPainted(false);
        jButton9.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton9MouseMoved(evt);
            }
        });
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 670, 50));

        jButton10.setBackground(new java.awt.Color(238, 112, 82));
        jButton10.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Agregar Detalle");
        jButton10.setBorder(null);
        jButton10.setFocusPainted(false);
        jButton10.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton10MouseMoved(evt);
            }
        });
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 760, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        this.setState(DetallePag.ICONIFIED);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jTFIdEmpleadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFIdEmpleadoKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jTFIdEmpleadoKeyTyped

    private void jTFMontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMontoKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jTFMontoKeyTyped

    private void jTFDetalleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDetalleKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFDetalleKeyTyped

    private void jButton9MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseMoved

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (!this.jTFIdEmpleado.getText().equals("")) {

            float total = 0;
            for (int i = 0; i < this.listaDetalle.size(); i++) {
                total += this.listaDetalle.get(i).getMonto();
            }

            int idMov = new MySQLConsultas().obtenerUltimoID("movimiento_financiero");

            idMov--;
            MovimientoFinanciero mov = null;
            MySQLMovimientoFinanciero sqlmov = new MySQLMovimientoFinanciero();

            mov = sqlmov.obtenerId(idMov);

            if (mov != null) {
                mov.setIdTipoTransaccion(2);
                mov.setMonto(total);

                if (mov.getMonto() < mov.getTotal()) {
                    mov.setTotal(mov.getTotal() - total);
                    sqlmov.insertarFechaActual(mov);
                } else {
                    JOptionPane.showMessageDialog(this, "No tienes los recursos para realizar el pago");
                    return;
                }

            }

            int idPago = new MySQLConsultas().obtenerUltimoID("pago");

            Pago pago = new Pago();
            pago.setPago(total);
            pago.setIdEmpleado(Integer.parseInt(this.jTFIdEmpleado.getText()));

            MySQLPago mysqlPago = new MySQLPago();

            mysqlPago.insertar(pago);

            pago = mysqlPago.obtenerId(idPago);

            for (int i = 0; i < this.listaDetalle.size(); i++) {
                listaDetalle.get(i).setIdPago(pago.getIdPago());
                MySQLDetallePago mysqlDetallePago = new MySQLDetallePago();
                mysqlDetallePago.insertar(listaDetalle.get(i));
            }

            JOptionPane.showMessageDialog(this, "Se realizo el pago correctamente");
        } else {
            JOptionPane.showMessageDialog(this, "Llena todos los campos");
        }    // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseMoved

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (!this.jTFIdEmpleado.getText().equals("") && !this.jTFMonto.getText().equals("") && !this.jTFDetalle.getText().equals("")) {
            Empleado emp = new MySQLEmpleado().obtenerId(Integer.parseInt(this.jTFIdEmpleado.getText()));

            if (emp != null) {
                DetallePago detPago = new DetallePago();
                detPago.setMonto(Float.parseFloat(this.jTFMonto.getText()));
                detPago.setDetalle(this.jTFDetalle.getText());

                listaDetalle.add(detPago);
                JOptionPane.showMessageDialog(this, "Se agrego correctamente");
                this.jTFDetalle.setText("");
                this.jTFMonto.setText("");
                this.jTFIdEmpleado.setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "El ID del empleado no existe");
            }

        } else {
            JOptionPane.showMessageDialog(this, "Llena todos los campos");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearPago.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearPago().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTFDetalle;
    private javax.swing.JTextField jTFIdEmpleado;
    private javax.swing.JTextField jTFMonto;
    // End of variables declaration//GEN-END:variables
}
