/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas;

import java.awt.Color;
import static java.awt.Color.white;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import proyectobd.controladores.ControladorAsistencia;
import proyectobd.controladores.ControladorEmpleado;
import proyectobd.controladores.ControladorHorario;
import proyectobd.dao.mysql.MySQLInasistencia;
import proyectobd.excepciones.Excepcion;
import proyectobd.modelos.Asistencia;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.Horario;
import proyectobd.modelos.Inasistencia;
import proyectobd.vistas.modulo.compraVenta.Venta;

/**
 *
 * @author israe
 */
public class Login extends javax.swing.JFrame {

    private ControladorEmpleado controladorEmpleado;
    private ControladorAsistencia controladorAsistencia;
    private ControladorHorario controladorHorario;
    private Empleado empleado;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.controladorEmpleado = new ControladorEmpleado();
        this.controladorAsistencia = new ControladorAsistencia();
        this.controladorHorario = new ControladorHorario();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPIngreso = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTFUser = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jPFContra = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 30, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 30, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 50));

        jPIngreso.setBackground(new java.awt.Color(255, 255, 255));
        jPIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPIngreso.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(238, 112, 82));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(238, 112, 82));
        jLabel1.setText("Contraseña");
        jPIngreso.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("ID Empleado");
        jPIngreso.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_User_96px_2.png"))); // NOI18N
        jPIngreso.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 90));

        jTFUser.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFUser.setForeground(new java.awt.Color(153, 153, 153));
        jTFUser.setBorder(null);
        jTFUser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFUserFocusGained(evt);
            }
        });
        jTFUser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFUserKeyTyped(evt);
            }
        });
        jPIngreso.add(jTFUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 240, 40));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator1.setForeground(new java.awt.Color(153, 153, 153));
        jPIngreso.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 290, 10));

        jPFContra.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jPFContra.setForeground(new java.awt.Color(153, 153, 153));
        jPFContra.setBorder(null);
        jPFContra.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFContraFocusGained(evt);
            }
        });
        jPIngreso.add(jPFContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 240, 40));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jPIngreso.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 290, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jPIngreso.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 265, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Key_32px.png"))); // NOI18N
        jPIngreso.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 375, -1, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/Enter_OFF.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/Enter_ON.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPIngreso.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 460, 160, 60));

        getContentPane().add(jPIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        int respuesta = JOptionPane.showConfirmDialog(null, "Desea salir de la aplicacion?", "Salir", JOptionPane.YES_NO_OPTION);
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        this.setState(Login.ICONIFIED);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTFUserKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFUserKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFUserKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contra = new String(this.jPFContra.getPassword());
        if (!this.jTFUser.getText().equals("") && !contra.equals("")) {
            int id = Integer.parseInt(this.jTFUser.getText());
            this.empleado = controladorEmpleado.getSesion(id, contra);

            if (this.empleado != null) {
                Horario horario = controladorHorario.obtenerHorario(this.empleado.getIdHorario());

                String[] partirHora = horario.getEntrada().split(":");
                int hora = Integer.parseInt(partirHora[0]);
                if (hora < 23) {
                    hora += 1;
                }
                String aux = String.valueOf(hora) + ":" + partirHora[1] + ":" + partirHora[2];
                horario.setEntrada(aux);

                Calendar calendario = Calendar.getInstance();
                String horaActual = calendario.get(Calendar.HOUR_OF_DAY) + ":" + calendario.get(Calendar.MINUTE) + ":" + calendario.get(Calendar.SECOND);

                try {
                    Asistencia asistencia;

                    asistencia = controladorAsistencia.obtenerPorFechayID(empleado.getIdEmpleado());
                    
                    if(asistencia != null){
                        horaActual = asistencia.getHora_entrada();
                        if(asistencia.getHora_salida() != null){
                            JOptionPane.showMessageDialog(this,"Ya has marcado salida vuelve el siguiente dia");
                            this.jTFUser.setText("");
                            this.jPFContra.setText("");
                            return;
                        }
                    }
                    DateFormat dateFormat = new SimpleDateFormat("hh:mm");

                    Date DHoraEntrada = dateFormat.parse(horario.getEntrada());
                    Date DHoraActual = dateFormat.parse(horaActual);
                    
                    

                    if (DHoraEntrada.compareTo(DHoraActual) > 0) {

                        if (asistencia == null) {
                            asistencia = new Asistencia();
                            asistencia.setIdEmpleado(this.empleado.getIdEmpleado());
                            controladorAsistencia.insertarAsistencia(asistencia);
                        }
                        switch (this.empleado.getIdPuesto()) {
                            case 1: // Vendedor
                                this.dispose();
                                Venta.info = this.empleado;
                                Venta venta = new Venta();
                                venta.setVisible(true);
                                break;
                            case 2: // Supervisor
                            case 3: //Jefe
                            case 4: //Gerente
                            case 5: // Contador
                                this.dispose();
                                Admin admin = new Admin(this.empleado);
                                admin.setVisible(true);
                                break;
                            case 6:
                                break;
                        }
                    } else {
                        try {
                            MySQLInasistencia myinasistencia = new MySQLInasistencia();

                            Inasistencia inasistencia = new MySQLInasistencia().obtenerIdyporFecha(this.empleado.getIdEmpleado());

                            if (inasistencia == null) {
                                inasistencia = new Inasistencia();
                                inasistencia.setIdEmpleado(this.empleado.getIdEmpleado());
                                inasistencia.setIdTipoInasistencia(2);
                                myinasistencia.insertar(inasistencia);
                            }
                            JOptionPane.showMessageDialog(this, "No se permite entrar despues de una hora tarde vuelve proximo dia");
                            System.exit(0);
                        } catch (Excepcion e) {
                            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            System.exit(0);
                        }
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuario y contraseña es incorrecta / intente de nuevo", "Error", JOptionPane.ERROR_MESSAGE);
                this.jTFUser.setText("");
                this.jPFContra.setText("");
            }

        } else {
            if (this.jTFUser.getText().equals("") || this.jTFUser.getText().equals("0")) {
                this.jTFUser.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (contra.equals("")) {
                this.jPFContra.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            this.jTFUser.setText("");
            this.jPFContra.setText("");
            JOptionPane.showMessageDialog(null, "Ingresa los campos para iniciar sesion", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTFUserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFUserFocusGained
        this.jTFUser.setBorder(BorderFactory.createLineBorder(white, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTFUserFocusGained

    private void jPFContraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFContraFocusGained
        this.jPFContra.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jPFContraFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPFContra;
    private javax.swing.JPanel jPIngreso;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFUser;
    // End of variables declaration//GEN-END:variables
}
