/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.empleados;

import java.awt.Color;
import static java.awt.Color.white;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import proyectobd.controladores.ControladorHorario;
import proyectobd.controladores.ControladorPersona;
import proyectobd.controladores.ControladorPuesto;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.Horario;
import proyectobd.modelos.Persona;
import proyectobd.modelos.Puesto;

/**
 *
 * @author israe
 */
public class CrearHorario extends javax.swing.JFrame {

    ControladorHorario controladorHorario;
    private String regreso;
    private Empleado info;

    /**
     * Creates new form CrearH
     */
    public CrearHorario() {
        initComponents();
        this.setLocationRelativeTo(null);
        controladorHorario = new ControladorHorario();
    }

    public CrearHorario(String regreso,Empleado info) {
        initComponents();
        this.setLocationRelativeTo(null);
        controladorHorario = new ControladorHorario();
        this.regreso = regreso;
        
        this.info = info;
        
        this.jLabel14.setText(String.valueOf(this.info.getIdEmpleado()));
        Persona persona = new ControladorPersona().obtenerPorID(this.info.getIdPersona());
        this.jLabel5.setText(persona.getNombre());
        Puesto puesto = new ControladorPuesto().buscarPuesto(this.info.getIdPuesto());
        this.jLabel7.setText(puesto.getNombre());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTFSegEntrada = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jTFHoraEntrada = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jTFMinEntrada = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTFHoraSalida = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTFMinSalida = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTFSegSalida = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jBInsertar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator2.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 10));

        jSeparator3.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator3.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 10));

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("Nombre Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator4.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 10));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("Puesto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_empleado32px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_User_96px_2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 90));

        jLabel14.setBackground(new java.awt.Color(238, 112, 82));
        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 112, 82));
        jLabel14.setText("ID Empleado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 580));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_regreso_32px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Nuevo Horario");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 370, 60));

        jLabel11.setBackground(new java.awt.Color(238, 112, 82));
        jLabel11.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(238, 112, 82));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("seg");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 50, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_hora_32px.png"))); // NOI18N
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 40, -1));

        jTFSegEntrada.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFSegEntrada.setBorder(null);
        jTFSegEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFSegEntradaFocusGained(evt);
            }
        });
        jTFSegEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSegEntradaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFSegEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 30, 40));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 30, 10));

        jTFHoraEntrada.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFHoraEntrada.setBorder(null);
        jTFHoraEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFHoraEntradaFocusGained(evt);
            }
        });
        jTFHoraEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFHoraEntradaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 30, 40));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 30, 10));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 30, 10));

        jTFMinEntrada.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFMinEntrada.setBorder(null);
        jTFMinEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFMinEntradaFocusGained(evt);
            }
        });
        jTFMinEntrada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFMinEntradaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFMinEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 30, 40));

        jLabel17.setBackground(new java.awt.Color(238, 112, 82));
        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Hora de Salida");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 430, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_hora_32px.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 40, -1));

        jTFHoraSalida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFHoraSalida.setBorder(null);
        jTFHoraSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFHoraSalidaFocusGained(evt);
            }
        });
        jTFHoraSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFHoraSalidaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 30, 40));

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 30, 10));

        jTFMinSalida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFMinSalida.setBorder(null);
        jTFMinSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFMinSalidaFocusGained(evt);
            }
        });
        jTFMinSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFMinSalidaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFMinSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 30, 40));

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 30, 10));

        jTFSegSalida.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFSegSalida.setBorder(null);
        jTFSegSalida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFSegSalidaFocusGained(evt);
            }
        });
        jTFSegSalida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFSegSalidaKeyTyped(evt);
            }
        });
        jPanel2.add(jTFSegSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 30, 40));

        jSeparator10.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, 30, 10));

        jLabel19.setBackground(new java.awt.Color(238, 112, 82));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 112, 82));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Hora de Entrada");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 430, 30));

        jLabel20.setBackground(new java.awt.Color(238, 112, 82));
        jLabel20.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(238, 112, 82));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("hora");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 50, 30));

        jLabel21.setBackground(new java.awt.Color(238, 112, 82));
        jLabel21.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(238, 112, 82));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("min");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 50, 30));

        jLabel22.setBackground(new java.awt.Color(238, 112, 82));
        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 112, 82));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("seg");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 50, 30));

        jLabel23.setBackground(new java.awt.Color(238, 112, 82));
        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(238, 112, 82));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("hora");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 50, 30));

        jLabel24.setBackground(new java.awt.Color(238, 112, 82));
        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(238, 112, 82));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("min");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 50, 30));

        jBInsertar.setBackground(new java.awt.Color(238, 112, 82));
        jBInsertar.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jBInsertar.setForeground(new java.awt.Color(255, 255, 255));
        jBInsertar.setText("Ingresar");
        jBInsertar.setBorder(null);
        jBInsertar.setFocusPainted(false);
        jBInsertar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBInsertarMouseMoved(evt);
            }
        });
        jBInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBInsertarMouseExited(evt);
            }
        });
        jBInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBInsertarActionPerformed(evt);
            }
        });
        jPanel2.add(jBInsertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, 680, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if (this.regreso.equalsIgnoreCase("IngresoEmpleado")) {
            this.dispose();
            this.dispose();
            IngresoEmpleado ingresoEmpleado = new IngresoEmpleado("ModuloEmpleados",this.info);
            ingresoEmpleado.setVisible(true);
        }
        if (this.regreso.equalsIgnoreCase("ModificarEmpleado")) {
            this.dispose();
            ModificarEmpleado modificarEmpleado = new ModificarEmpleado("ModuloEmpleados",this.info);
            modificarEmpleado.setVisible(true);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(IngresoEmpleado.ICONIFIED);//Arreglar
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jBInsertarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInsertarMouseMoved
        jBInsertar.setBackground(new Color(204, 51, 0));
    }//GEN-LAST:event_jBInsertarMouseMoved

    private void jBInsertarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBInsertarMouseExited
        jBInsertar.setBackground(new Color(238, 112, 82));
    }//GEN-LAST:event_jBInsertarMouseExited

    private void jTFHoraEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFHoraEntradaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFHoraEntrada.getText();
        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 24) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFHoraEntradaKeyTyped

    private void jTFMinEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMinEntradaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFMinEntrada.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 60) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFMinEntradaKeyTyped

    private void jTFSegEntradaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSegEntradaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFSegEntrada.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 60) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFSegEntradaKeyTyped

    private void jTFHoraSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFHoraSalidaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFHoraSalida.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 24) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFHoraSalidaKeyTyped

    private void jTFMinSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMinSalidaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFMinSalida.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 60) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFMinSalidaKeyTyped

    private void jTFSegSalidaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFSegSalidaKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFSegSalida.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 2 || Integer.parseInt(cadena + a) > 60) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFSegSalidaKeyTyped
    private void vaciarCampos() {
        this.jTFHoraEntrada.setText("");
        this.jTFMinEntrada.setText("");
        this.jTFSegEntrada.setText("");
        this.jTFHoraSalida.setText("");
        this.jTFMinSalida.setText("");
        this.jTFSegSalida.setText("");
    }
    private void jBInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBInsertarActionPerformed
        if (!this.jTFHoraEntrada.getText().equals("") && !this.jTFMinEntrada.getText().equals("") && !this.jTFSegEntrada.getText().equals("") && !this.jTFHoraSalida.getText().equals("")
                && !this.jTFMinSalida.getText().equals("") && !this.jTFSegSalida.getText().equals("")) {

            Horario nuevo = new Horario();
            nuevo.setEntrada(controladorHorario.parseHora(this.jTFHoraEntrada.getText(), this.jTFMinEntrada.getText(), this.jTFSegEntrada.getText()));
            nuevo.setSalida(controladorHorario.parseHora(this.jTFHoraSalida.getText(), this.jTFMinSalida.getText(), this.jTFSegSalida.getText()));

            if (controladorHorario.buscarPorHorarios(nuevo) == null) {
                controladorHorario.insertarHorario(nuevo.getEntrada(), nuevo.getSalida());
                vaciarCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Este horario ya esta registrado", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            if (this.jTFHoraEntrada.getText().equals("")) {
                this.jTFHoraEntrada.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFMinEntrada.getText().equals("")) {
                this.jTFMinEntrada.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFSegEntrada.getText().equals("")) {
                this.jTFSegEntrada.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFHoraSalida.getText().equals("")) {
                this.jTFHoraSalida.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFMinSalida.getText().equals("")) {
                this.jTFMinSalida.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFSegSalida.getText().equals("")) {
                this.jTFSegSalida.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            String mensaje = "Rellene todos los campos.";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBInsertarActionPerformed

    private void jTFHoraEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFHoraEntradaFocusGained
        this.jTFHoraEntrada.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFHoraEntradaFocusGained

    private void jTFMinEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMinEntradaFocusGained
        this.jTFMinEntrada.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFMinEntradaFocusGained

    private void jTFSegEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSegEntradaFocusGained
        this.jTFSegEntrada.setBorder(BorderFactory.createLineBorder(white, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSegEntradaFocusGained

    private void jTFHoraSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFHoraSalidaFocusGained
        this.jTFHoraSalida.setBorder(BorderFactory.createLineBorder(white, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTFHoraSalidaFocusGained

    private void jTFMinSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFMinSalidaFocusGained
        this.jTFMinSalida.setBorder(BorderFactory.createLineBorder(white, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTFMinSalidaFocusGained

    private void jTFSegSalidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFSegSalidaFocusGained
        this.jTFSegSalida.setBorder(BorderFactory.createLineBorder(white, 1));        // TODO add your handling code here:
    }//GEN-LAST:event_jTFSegSalidaFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearHorario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearHorario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBInsertar;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFHoraEntrada;
    private javax.swing.JTextField jTFHoraSalida;
    private javax.swing.JTextField jTFMinEntrada;
    private javax.swing.JTextField jTFMinSalida;
    private javax.swing.JTextField jTFSegEntrada;
    private javax.swing.JTextField jTFSegSalida;
    // End of variables declaration//GEN-END:variables
}
