/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectobd.vistas.modulo.empleados;

import java.awt.Color;
import static java.awt.Color.red;
import static java.awt.Color.white;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import proyectobd.controladores.ControladorEmpleado;
import proyectobd.controladores.ControladorHorario;
import proyectobd.controladores.ControladorPersona;
import proyectobd.controladores.ControladorPuesto;
import proyectobd.dao.mysql.MySQLAsistencia;
import proyectobd.dao.mysql.MySQLInasistencia;
import proyectobd.excepciones.Excepcion;
import proyectobd.modelos.Asistencia;
import proyectobd.modelos.Empleado;
import proyectobd.modelos.Horario;
import proyectobd.modelos.Inasistencia;
import proyectobd.modelos.Persona;
import proyectobd.modelos.Puesto;
import proyectobd.vistas.Admin;
import proyectobd.vistas.Login;
import proyectobd.vistas.custom.CustomUI;

/**
 *
 * @author israe
 */
public class IngresoEmpleado extends javax.swing.JFrame {

    private ControladorEmpleado controladorEmpleado;
    private ControladorPuesto controladorPuesto;
    private ControladorHorario controladorHorario;
    private ControladorPersona controladorPersona;

    private String regreso;

    private Empleado info;

    /**
     * Creates new form Ingreso
     */
    public IngresoEmpleado() {
        initComponents();

        this.setLocationRelativeTo(null);

        this.jCBPuesto.setBackground(new java.awt.Color(255, 255, 255));
        this.jCBPuesto.setUI(new CustomUI());
        this.jCBHorario.setBackground(new java.awt.Color(255, 255, 255));
        this.jCBHorario.setUI(new CustomUI());

        controladorEmpleado = new ControladorEmpleado();
        this.jTFIdEmpleado.setText(String.valueOf(controladorEmpleado.obtenerIdSiguiente()));
        this.jTFIdEmpleado.setEnabled(false);

        controladorPersona = new ControladorPersona();

        controladorPuesto = new ControladorPuesto();
        ArrayList<Puesto> puestos = controladorPuesto.obtenerPuestos();

        for (int i = 0; i < puestos.size(); i++) {
            jCBPuesto.addItem(puestos.get(i).getNombre());
        }

        controladorHorario = new ControladorHorario();
        ArrayList<Horario> horarios = controladorHorario.obtenerHorarios();

        for (int i = 0; i < horarios.size(); i++) {
            jCBHorario.addItem(horarios.get(i).getEntrada() + " a " + horarios.get(i).getSalida());
        }

        jDCFecha.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
    }

    public IngresoEmpleado(String regreso, Empleado info) {
        initComponents();
        this.setLocationRelativeTo(null);

        this.regreso = regreso;
        this.info = info;

        this.jLabel14.setText(String.valueOf(this.info.getIdEmpleado()));
        Persona persona = new ControladorPersona().obtenerPorID(this.info.getIdPersona());
        this.jLabel5.setText(persona.getNombre());
        Puesto puesto = new ControladorPuesto().buscarPuesto(this.info.getIdPuesto());
        this.jLabel7.setText(puesto.getNombre());

        this.jCBPuesto.setBackground(new java.awt.Color(255, 255, 255));
        this.jCBPuesto.setUI(new CustomUI());
        this.jCBHorario.setBackground(new java.awt.Color(255, 255, 255));
        this.jCBHorario.setUI(new CustomUI());

        controladorEmpleado = new ControladorEmpleado();
        this.jTFIdEmpleado.setText(String.valueOf(controladorEmpleado.obtenerIdSiguiente()));
        this.jTFIdEmpleado.setEnabled(false);

        controladorPersona = new ControladorPersona();

        controladorPuesto = new ControladorPuesto();
        ArrayList<Puesto> puestos = controladorPuesto.obtenerPuestos();

        for (int i = 0; i < puestos.size(); i++) {
            jCBPuesto.addItem(puestos.get(i).getNombre());
        }

        controladorHorario = new ControladorHorario();
        ArrayList<Horario> horarios = controladorHorario.obtenerHorarios();

        for (int i = 0; i < horarios.size(); i++) {
            jCBHorario.addItem(horarios.get(i).getEntrada() + " a " + horarios.get(i).getSalida());
        }

        jDCFecha.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jTFIdEmpleado = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTFDpi = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTFNit = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jTFApellido = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTFDireccion = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jPFContrasenia = new javax.swing.JPasswordField();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel32 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jSeparator15 = new javax.swing.JSeparator();
        jLabel36 = new javax.swing.JLabel();
        jCBPuesto = new javax.swing.JComboBox<>();
        jCBHorario = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jDCFecha = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator2.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 230, 10));

        jSeparator3.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator3.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 230, 10));

        jLabel5.setBackground(new java.awt.Color(238, 112, 82));
        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(238, 112, 82));
        jLabel5.setText("Nombre Apellido");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 180, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(238, 112, 82));
        jSeparator4.setForeground(new java.awt.Color(238, 112, 82));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 230, 10));

        jLabel7.setBackground(new java.awt.Color(238, 112, 82));
        jLabel7.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(238, 112, 82));
        jLabel7.setText("Puesto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 180, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_empleado32px.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_User_96px_2.png"))); // NOI18N
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, 90));

        jLabel14.setBackground(new java.awt.Color(238, 112, 82));
        jLabel14.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(238, 112, 82));
        jLabel14.setText("ID Empleado");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 180, 30));

        jButton3.setBackground(new java.awt.Color(238, 112, 82));
        jButton3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Cerrar Sesion ");
        jButton3.setBorder(null);
        jButton3.setFocusPainted(false);
        jButton3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton3MouseMoved(evt);
            }
        });
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 230, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 700));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_regreso_32px.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 30, 50));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 30, 50));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 760, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(238, 112, 82));
        jLabel16.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(238, 112, 82));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Informacion de empleado");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 370, -1));

        jLabel3.setBackground(new java.awt.Color(238, 112, 82));
        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("ID Empleado");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 120, 30));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 120, 10));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTFIdEmpleado.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFIdEmpleado.setBorder(null);
        jPanel2.add(jTFIdEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 70, 40));

        jLabel17.setBackground(new java.awt.Color(238, 112, 82));
        jLabel17.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(238, 112, 82));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("DPI");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 290, 30));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_id_32px.png"))); // NOI18N
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, -1, -1));

        jTFDpi.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFDpi.setForeground(new java.awt.Color(153, 153, 153));
        jTFDpi.setBorder(null);
        jTFDpi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDpiFocusGained(evt);
            }
        });
        jTFDpi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTFDpiMouseClicked(evt);
            }
        });
        jTFDpi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTFDpiKeyTyped(evt);
            }
        });
        jPanel2.add(jTFDpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 240, 40));

        jSeparator6.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator6.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 290, 10));

        jLabel19.setBackground(new java.awt.Color(238, 112, 82));
        jLabel19.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(238, 112, 82));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("NIT");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 70, 190, 30));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_nit_32px.png"))); // NOI18N
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 112, -1, 20));

        jTFNit.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFNit.setForeground(new java.awt.Color(153, 153, 153));
        jTFNit.setBorder(null);
        jTFNit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNitFocusGained(evt);
            }
        });
        jPanel2.add(jTFNit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 140, 40));

        jSeparator7.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator7.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 190, 10));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jTFNombre.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFNombre.setForeground(new java.awt.Color(153, 153, 153));
        jTFNombre.setBorder(null);
        jTFNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFNombreFocusGained(evt);
            }
        });
        jPanel2.add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 260, 40));

        jSeparator8.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator8.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 310, 10));

        jLabel22.setBackground(new java.awt.Color(238, 112, 82));
        jLabel22.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(238, 112, 82));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Nombres");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 310, 30));

        jLabel23.setBackground(new java.awt.Color(238, 112, 82));
        jLabel23.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(238, 112, 82));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Nombres");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 310, 30));

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_customer_32px_1.png"))); // NOI18N
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        jLabel26.setBackground(new java.awt.Color(238, 112, 82));
        jLabel26.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(238, 112, 82));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Apellidos");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 310, 30));

        jSeparator10.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator10.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 310, 10));

        jTFApellido.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFApellido.setForeground(new java.awt.Color(153, 153, 153));
        jTFApellido.setBorder(null);
        jTFApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFApellidoFocusGained(evt);
            }
        });
        jPanel2.add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 200, 260, 40));

        jLabel24.setBackground(new java.awt.Color(238, 112, 82));
        jLabel24.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(238, 112, 82));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Dirección");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 310, 30));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_fecha_32px.png"))); // NOI18N
        jPanel2.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jTFDireccion.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jTFDireccion.setForeground(new java.awt.Color(153, 153, 153));
        jTFDireccion.setBorder(null);
        jTFDireccion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTFDireccionFocusGained(evt);
            }
        });
        jPanel2.add(jTFDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 260, 40));

        jSeparator9.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator9.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 310, 10));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icons8_Key_32px.png"))); // NOI18N
        jPanel2.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, -1, -1));

        jLabel29.setBackground(new java.awt.Color(238, 112, 82));
        jLabel29.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(238, 112, 82));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Contraseña");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 310, 30));

        jSeparator11.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator11.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 340, 310, 10));

        jPFContrasenia.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jPFContrasenia.setForeground(new java.awt.Color(153, 153, 153));
        jPFContrasenia.setBorder(null);
        jPFContrasenia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPFContraseniaFocusGained(evt);
            }
        });
        jPanel2.add(jPFContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 260, 40));

        jSeparator12.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator12.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 440, 250, 10));

        jLabel32.setBackground(new java.awt.Color(238, 112, 82));
        jLabel32.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(238, 112, 82));
        jLabel32.setText("Fecha Inicio");
        jPanel2.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 310, 30));

        jLabel31.setBackground(new java.awt.Color(238, 112, 82));
        jLabel31.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(238, 112, 82));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel31.setText("Puesto");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, 310, 30));

        jSeparator15.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator15.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator15, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 310, 10));

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobd/vistas/imagenes/icon_direccion_32px.png"))); // NOI18N
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        jCBPuesto.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jCBPuesto.setForeground(new java.awt.Color(238, 112, 82));
        jCBPuesto.setBorder(null);
        jCBPuesto.setFocusable(false);
        jCBPuesto.setOpaque(false);
        jCBPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBPuestoActionPerformed(evt);
            }
        });
        jPanel2.add(jCBPuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 310, 30));

        jCBHorario.setFont(new java.awt.Font("Microsoft JhengHei", 0, 14)); // NOI18N
        jCBHorario.setForeground(new java.awt.Color(238, 112, 82));
        jCBHorario.setBorder(null);
        jCBHorario.setFocusable(false);
        jCBHorario.setOpaque(false);
        jPanel2.add(jCBHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 310, 30));

        jLabel37.setBackground(new java.awt.Color(238, 112, 82));
        jLabel37.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(238, 112, 82));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Horario");
        jPanel2.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 310, 30));

        jSeparator16.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator16.setForeground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 310, 10));

        jButton1.setBackground(new java.awt.Color(238, 112, 82));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Nuevo Horario");
        jButton1.setBorder(null);
        jButton1.setFocusPainted(false);
        jButton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton1MouseMoved(evt);
            }
        });
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 510, 310, 30));

        jButton2.setBackground(new java.awt.Color(238, 112, 82));
        jButton2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ingresar");
        jButton2.setBorder(null);
        jButton2.setFocusPainted(false);
        jButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton2MouseMoved(evt);
            }
        });
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 570, 680, 50));

        jDCFecha.setBackground(new java.awt.Color(255, 255, 255));
        jDCFecha.setForeground(new java.awt.Color(238, 112, 82));
        jPanel2.add(jDCFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 250, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 760, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        if (this.regreso.equalsIgnoreCase("ModuloEmpleados")) {
            this.dispose();
            ModuloEmpleados modEmpleado = new ModuloEmpleados("admin", this.info);
            modEmpleado.setVisible(true);
        }
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        this.setState(IngresoEmpleado.ICONIFIED);//Arreglar
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
        jButton2.setBackground(new Color(238, 112, 82));
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton2MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseMoved
        jButton2.setBackground(new Color(204, 51, 0));
    }//GEN-LAST:event_jButton2MouseMoved

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        jButton1.setBackground(new Color(238, 112, 82));
    }//GEN-LAST:event_jButton1MouseExited

    private void jButton1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseMoved
        jButton1.setBackground(new Color(204, 51, 0));
    }//GEN-LAST:event_jButton1MouseMoved

    private void jCBPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBPuestoActionPerformed

    private void jTFDpiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDpiKeyTyped
        char a = evt.getKeyChar();
        String cadena = this.jTFDpi.getText();

        if (!Character.isDigit(a) || cadena.length() + 1 > 13) {
            evt.consume();
        }
    }//GEN-LAST:event_jTFDpiKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String contra = new String(this.jPFContrasenia.getPassword());
        Empleado empleado = null;
        if (!this.jTFDpi.getText().equals("") && !this.jTFIdEmpleado.getText().equals("") && !this.jTFNit.getText().equals("")
                && !this.jTFNombre.getText().equals("") && !this.jTFApellido.getText().equals("") && !this.jTFDireccion.getText().equals("") && !contra.equals("") && !(this.jTFDpi.getText().length() < 13)) {
            //Parse persona
            Persona persona = controladorPersona.obtenerIDporDPI(this.jTFDpi.getText().trim());
            if (persona == null) {
                persona = new Persona(0, this.jTFDpi.getText().trim(), this.jTFNombre.getText().trim(), this.jTFApellido.getText().trim(),
                        this.jTFDireccion.getText().trim(), this.jTFNit.getText().trim());
                controladorPersona.insertarPersona(persona);
            }
            persona = controladorPersona.obtenerIDporDPI(this.jTFDpi.getText().trim());

            if (persona != null) {
                Date fecha = this.jDCFecha.getDate();
                empleado = controladorEmpleado.parseEmpleado(0, contra, fecha, persona.getIdPersona(), controladorPuesto.buscarIdPuesto((String) this.jCBPuesto.getSelectedItem()), controladorHorario.buscarIdHorario((String) this.jCBHorario.getSelectedItem()));
            } else {
                JOptionPane.showMessageDialog(null, "Avise al departamento de informatica");
            }

            controladorEmpleado.insertarEmpleado(empleado);
            borrarInputs();
            JOptionPane.showMessageDialog(null, "Se ingreso correctamente");

        } else {
            String mensaje = "";
            if (this.jTFDpi.getText().length() < 13) {
                mensaje = "En DPI ingrese 13 digitos. | ";
            }
            if (this.jTFDpi.getText().equals("")) {

                this.jTFDpi.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFNit.getText().equals("")) {
                this.jTFNit.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFNombre.getText().equals("")) {
                this.jTFNombre.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFApellido.getText().equals("")) {
                this.jTFApellido.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (this.jTFDireccion.getText().equals("")) {
                this.jTFDireccion.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            if (contra.equals("")) {
                this.jPFContrasenia.setBorder(BorderFactory.createLineBorder(new Color(238, 112, 82), 1));
            }
            mensaje += "Rellene todos los campos.";
            JOptionPane.showMessageDialog(null, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    private void borrarInputs() {
        this.jTFDpi.setText("");
        this.jTFNit.setText("");
        this.jTFNombre.setText("");
        this.jTFApellido.setText("");
        this.jTFDireccion.setText("");
        this.jPFContrasenia.setText("");
        this.jDCFecha.setDate(java.sql.Date.valueOf(java.time.LocalDate.now()));
        this.jTFIdEmpleado.setEnabled(true);
        this.jTFIdEmpleado.setText(String.valueOf(controladorEmpleado.obtenerIdSiguiente()));
        this.jTFIdEmpleado.setEnabled(false);
        this.jCBPuesto.setSelectedIndex(0);
        this.jCBHorario.setSelectedIndex(0);
    }

    private void jTFDpiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFDpiMouseClicked

    }//GEN-LAST:event_jTFDpiMouseClicked

    private void jTFDpiFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDpiFocusGained
        this.jTFDpi.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFDpiFocusGained

    private void jTFNitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNitFocusGained
        this.jTFNit.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFNitFocusGained

    private void jTFNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFNombreFocusGained
        this.jTFNombre.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFNombreFocusGained

    private void jTFApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFApellidoFocusGained
        this.jTFApellido.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFApellidoFocusGained

    private void jTFDireccionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTFDireccionFocusGained
        this.jTFDireccion.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jTFDireccionFocusGained

    private void jPFContraseniaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPFContraseniaFocusGained
        this.jPFContrasenia.setBorder(BorderFactory.createLineBorder(white, 1));
    }//GEN-LAST:event_jPFContraseniaFocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        CrearHorario nuevo = new CrearHorario("IngresoEmpleado", this.info);
        nuevo.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseMoved
        jButton3.setBackground(new Color(204, 51, 0));
    }//GEN-LAST:event_jButton3MouseMoved

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        jButton3.setBackground(new Color(238, 112, 82));
    }//GEN-LAST:event_jButton3MouseExited

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Horario horario = controladorHorario.obtenerHorario(this.info.getIdHorario());

        if (horario != null) {
            Calendar calendario = Calendar.getInstance();
            String horaActual = calendario.get(Calendar.HOUR_OF_DAY) + ":" + calendario.get(Calendar.MINUTE) + ":" + calendario.get(Calendar.SECOND);
            /*System.out.println("horaActual: " + horaActual);
            System.out.println("HoraSalida:" + horario.getSalida());*/

            try {
                DateFormat dateFormat = new SimpleDateFormat("hh:mm");

                Date DHoraSalida = dateFormat.parse(horario.getSalida());
                Date DHoraActual = dateFormat.parse(horaActual);

                if (DHoraSalida.compareTo(DHoraActual) > 0) {
                    int respuesta = JOptionPane.showConfirmDialog(null, "Tu hora de salida es: " + horario.getSalida() + ". Estas seguro que deseas salir? (se te contara como inasistencia)", "Cerrando Sesion", JOptionPane.YES_NO_OPTION);
                    if (respuesta == 0) {
                        try {
                            Inasistencia inasistencia = new Inasistencia();
                            inasistencia.setIdEmpleado(this.info.getIdEmpleado());
                            inasistencia.setIdTipoInasistencia(2);

                            MySQLInasistencia myinasistencia = new MySQLInasistencia();
                            myinasistencia.insertar(inasistencia);

                            MySQLAsistencia myasistencia = new MySQLAsistencia();
                            Asistencia aux = myasistencia.obtenerIdyFecha(this.info.getIdEmpleado());
                            aux.setHora_salida(horaActual);
                            myasistencia.modificar(aux);
                            JOptionPane.showMessageDialog(null, "Cerro Sesion correctamente");
                            dispose();
                            Login login = new Login();
                            login.setVisible(true);
                        } catch (Excepcion e) {
                            JOptionPane.showMessageDialog(null, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                            System.exit(0);
                        }
                    }
                } else {
                    MySQLAsistencia myasistencia = new MySQLAsistencia();
                    Asistencia aux = myasistencia.obtenerIdyFecha(this.info.getIdEmpleado());
                    aux.setHora_salida(horaActual);
                    myasistencia.modificar(aux);
                    JOptionPane.showMessageDialog(null, "Cerro Sesion correctamente");
                    dispose();
                    Login login = new Login();
                    login.setVisible(true);
                }

            } catch (ParseException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresoEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IngresoEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCBHorario;
    private javax.swing.JComboBox<String> jCBPuesto;
    private com.toedter.calendar.JDateChooser jDCFecha;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFContrasenia;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFDpi;
    private javax.swing.JTextField jTFIdEmpleado;
    private javax.swing.JTextField jTFNit;
    private javax.swing.JTextField jTFNombre;
    // End of variables declaration//GEN-END:variables
}
